<?xml version="1.0" encoding="utf-8"?><Database Name="ScFinances" Class="SqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.30.10.197;Initial Catalog=ScFinances;Persist Security Info=True;User ID=udata" SettingsObjectName="Layer.Data.Properties.Settings" SettingsPropertyName="ScFinancesConnectionString" Provider="System.Data.SqlClient" />
</Database>