//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=BvTester;Integrated Security=True")]
        public string BvTesterConnectionString {
            get {
                return ((string)(this["BvTesterConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=BvOveralls;Persist Security Info=T" +
            "rue;User ID=udata;Password=Turing2019")]
        public string BvOverallsConnectionString {
            get {
                return ((string)(this["BvOverallsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=BvBig;Persist Security Info=True;User I" +
            "D=udata;Password=udata123")]
        public string BvBigConnectionString {
            get {
                return ((string)(this["BvBigConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=BvnErp;User ID=udata;Password=Turi" +
            "ng2019")]
        public string BvnErpConnectionString {
            get {
                return ((string)(this["BvnErpConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=USER-20180704WQ\\SQL2014;Initial Catalog=Bv6Crm;Persist Security Info=" +
            "True;User ID=sa;Password=11")]
        public string Bv6CrmConnectionString {
            get {
                return ((string)(this["Bv6CrmConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=Bv3Crm;Persist Security Info=True;User " +
            "ID=udata")]
        public string Bv3CrmConnectionString {
            get {
                return ((string)(this["Bv3CrmConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=BvOrders;User ID=udata")]
        public string BvOrdersConnectionString {
            get {
                return ((string)(this["BvOrdersConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=BvSso;User ID=udata;Password=udata123")]
        public string BvSsoConnectionString {
            get {
                return ((string)(this["BvSsoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=BvOther;User ID=udata;Password=udata123" +
            "")]
        public string BvOtherConnectionString {
            get {
                return ((string)(this["BvOtherConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=BvScsm;Persist Security Info=True;User " +
            "ID=udata;Password=udata123")]
        public string BvScsmConnectionString {
            get {
                return ((string)(this["BvScsmConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=BvScsm3;Persist Security Info=True;User" +
            " ID=udata;Password=udata123")]
        public string BvScsm3ConnectionString {
            get {
                return ((string)(this["BvScsm3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=BvnEes;User ID=udata")]
        public string BvnEesConnectionString {
            get {
                return ((string)(this["BvnEesConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=VAERP;User ID=udata")]
        public string VAERPConnectionString {
            get {
                return ((string)(this["VAERPConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=BvnVrs;User ID=udata")]
        public string BvnVrsConnectionString {
            get {
                return ((string)(this["BvnVrsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=BvnOps;User ID=udata;Password=udata123")]
        public string BvnOpsConnectionString {
            get {
                return ((string)(this["BvnOpsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScChains;User ID=udata;Password=udata12" +
            "3;Encrypt=False;TrustServerCertificate=True")]
        public string ScChainsConnectionString {
            get {
                return ((string)(this["ScChainsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScPurchases;User ID=udata;Password=udat" +
            "a123;Encrypt=False;TrustServerCertificate=True")]
        public string ScPurchasesConnectionString {
            get {
                return ((string)(this["ScPurchasesConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScCustoms;User ID=udata;Encrypt=False;T" +
            "rustServerCertificate=True")]
        public string ScCustomsConnectionString {
            get {
                return ((string)(this["ScCustomsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScSales;User ID=udata;Password=udata123" +
            ";Encrypt=False;TrustServerCertificate=True")]
        public string ScSalesConnectionString {
            get {
                return ((string)(this["ScSalesConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScLogistics;User ID=udata;Password=udat" +
            "a123;Encrypt=False;TrustServerCertificate=True")]
        public string ScLogisticsConnectionString {
            get {
                return ((string)(this["ScLogisticsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScWms;User ID=udata;Password=udata123;E" +
            "ncrypt=False;TrustServerCertificate=True")]
        public string ScWmsConnectionString {
            get {
                return ((string)(this["ScWmsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScFinances;User ID=udata;Password=udata" +
            "123;Encrypt=False;TrustServerCertificate=True")]
        public string ScFinancesConnectionString {
            get {
                return ((string)(this["ScFinancesConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=BvnWss;Persist Security Info=True;User " +
            "ID=udata;Password=udata123")]
        public string BvnWssConnectionString {
            get {
                return ((string)(this["BvnWssConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=CvOss;User ID=udata")]
        public string CvOssConnectionString {
            get {
                return ((string)(this["CvOssConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=CvSso;Persist Security Info=True;User I" +
            "D=udata;Password=udata123")]
        public string CvSsoConnectionString {
            get {
                return ((string)(this["CvSsoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=IC360.CvOss;User ID=udata")]
        public string IC360_CvOssConnectionString {
            get {
                return ((string)(this["IC360_CvOssConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=IC360.CvSSO;Persist Security Info=True;" +
            "User ID=udata;Password=udata123")]
        public string IC360_CvSSOConnectionString {
            get {
                return ((string)(this["IC360_CvSSOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=IC360.BvSso;Persist Security Info=True;" +
            "User ID=udata;Password=udata123")]
        public string IC360_BvSsoConnectionString {
            get {
                return ((string)(this["IC360_BvSsoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=IC360.BvOrders;Persist Security Info=Tr" +
            "ue;User ID=udata;Password=udata123")]
        public string IC360_BvOrdersConnectionString {
            get {
                return ((string)(this["IC360_BvOrdersConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=IC360.VAOIP;Persist Security Info=True;" +
            "User ID=udata;Password=udata123")]
        public string IC360_VAOIPConnectionString {
            get {
                return ((string)(this["IC360_VAOIPConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=BvOveralls;User ID=udata;Password=" +
            "Turing2019")]
        public string BvOverallsConnectionString1 {
            get {
                return ((string)(this["BvOverallsConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=BvnErp;User ID=udata;Password=Turi" +
            "ng2019")]
        public string BvnErpConnectionString1 {
            get {
                return ((string)(this["BvnErpConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=BvOveralls;Persist Security Info=T" +
            "rue;User ID=udata")]
        public string BvOverallsConnectionString2 {
            get {
                return ((string)(this["BvOverallsConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=Bv3Crm;Persist Security Info=True;User " +
            "ID=udata;Password=udata123")]
        public string Bv3CrmConnectionString1 {
            get {
                return ((string)(this["Bv3CrmConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.51,6522;Initial Catalog=Bv3Crm;Persist Security Info=True;U" +
            "ser ID=u_bv;Password=G9RCzkV9hC4Gu6VF5QuZp6dxw8a9XErNTDR66Uwxww24hNBJtF")]
        public string Bv3CrmConnectionString2 {
            get {
                return ((string)(this["Bv3CrmConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScPurchases;Persist Security Info=True;" +
            "User ID=udata;Password=udata123")]
        public string ScPurchasesConnectionString1 {
            get {
                return ((string)(this["ScPurchasesConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScSales;Persist Security Info=True;User" +
            " ID=udata;Password=udata123")]
        public string ScSalesConnectionString1 {
            get {
                return ((string)(this["ScSalesConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=BvnWss;User ID=udata")]
        public string BvnWssConnectionString1 {
            get {
                return ((string)(this["BvnWssConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScWms;User ID=udata;Password=udata123;E" +
            "ncrypt=False;TrustServerCertificate=True")]
        public string ScWmsConnectionString1 {
            get {
                return ((string)(this["ScWmsConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=CvOss;Persist Security Info=True;User I" +
            "D=udata")]
        public string CvOssConnectionString1 {
            get {
                return ((string)(this["CvOssConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=BvSso;Persist Security Info=True;User I" +
            "D=udata;Password=udata123")]
        public string BvSsoConnectionString1 {
            get {
                return ((string)(this["BvSsoConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScSales;User ID=udata;Encrypt=False;Tru" +
            "stServerCertificate=True")]
        public string ScSalesConnectionString2 {
            get {
                return ((string)(this["ScSalesConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=CvOss;User ID=udata")]
        public string CvOssConnectionString3 {
            get {
                return ((string)(this["CvOssConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=CvOss;Persist Security Info=True;User I" +
            "D=udata;Password=udata123")]
        public string CvOssConnectionString4 {
            get {
                return ((string)(this["CvOssConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=BvnErp;User ID=udata")]
        public string BvnErpConnectionString2 {
            get {
                return ((string)(this["BvnErpConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=CvOss;Persist Security Info=True;User I" +
            "D=udata")]
        public string CvOssConnectionString2 {
            get {
                return ((string)(this["CvOssConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScSales;User ID=udata;Password=udata123" +
            ";Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string ScSalesConnectionString3 {
            get {
                return ((string)(this["ScSalesConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=CvOss;Persist Security Info=True;User I" +
            "D=udata;Password=udata123")]
        public string CvOssConnectionString5 {
            get {
                return ((string)(this["CvOssConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=BvnWss;Persist Security Info=True;User " +
            "ID=udata;Password=udata123")]
        public string BvnWssConnectionString2 {
            get {
                return ((string)(this["BvnWssConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=BvnErp;Persist Security Info=True;" +
            "User ID=udata;Password=Turing2019")]
        public string BvnErpConnectionString3 {
            get {
                return ((string)(this["BvnErpConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=IC360.CvOss;Persist Security Info=True;" +
            "User ID=udata")]
        public string IC360_CvOssConnectionString1 {
            get {
                return ((string)(this["IC360_CvOssConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=VASSO;User ID=udata;Password=udata123")]
        public string VASSOConnectionString {
            get {
                return ((string)(this["VASSOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=IC360.CvOss;Persist Security Info=True;" +
            "User ID=udata;Password=udata123")]
        public string IC360_CvOssConnectionString2 {
            get {
                return ((string)(this["IC360_CvOssConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=foricScCustoms;Persist Security In" +
            "fo=True;User ID=udata;Password=Turing2019")]
        public string ScCustomsConnectionString3 {
            get {
                return ((string)(this["ScCustomsConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScCustoms;Persist Security Info=True;Us" +
            "er ID=udata")]
        public string ScCustomsConnectionString1 {
            get {
                return ((string)(this["ScCustomsConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScCustoms;Persist Security Info=True;Us" +
            "er ID=udata")]
        public string ScCustomsConnectionString2 {
            get {
                return ((string)(this["ScCustomsConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScCustoms;Persist Security Info=True;Us" +
            "er ID=udata")]
        public string ScCustomsConnectionString4 {
            get {
                return ((string)(this["ScCustomsConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScCustoms;Persist Security Info=True;Us" +
            "er ID=udata")]
        public string ScCustomsConnectionString5 {
            get {
                return ((string)(this["ScCustomsConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.80.25;Initial Catalog=CvCS;Persist Security Info=True;User ID" +
            "=udata;Password=udata123")]
        public string CvCSConnectionString {
            get {
                return ((string)(this["CvCSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScCustoms;User ID=udata;Password=udata1" +
            "23")]
        public string ScCustomsConnectionString6 {
            get {
                return ((string)(this["ScCustomsConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScCustoms;Persist Security Info=True;Us" +
            "er ID=udata")]
        public string ScCustomsConnectionString7 {
            get {
                return ((string)(this["ScCustomsConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScCustoms;Persist Security Info=True;Us" +
            "er ID=udata")]
        public string ScCustomsConnectionString8 {
            get {
                return ((string)(this["ScCustomsConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScCustoms;User ID=udata;Connect Timeout" +
            "=30;Encrypt=False;TrustServerCertificate=False")]
        public string ScCustomsConnectionString9 {
            get {
                return ((string)(this["ScCustomsConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScCustoms;Persist Security Info=True;Us" +
            "er ID=udata")]
        public string ScCustomsConnectionString10 {
            get {
                return ((string)(this["ScCustomsConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.51,6522;Initial Catalog=foricScCustoms;Persist Security Inf" +
            "o=True;User ID=u_v0")]
        public string ScCustomsConnectionString11 {
            get {
                return ((string)(this["ScCustomsConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.51,6522;Initial Catalog=foricScCustoms;User ID=u_v0")]
        public string ScCustomsConnectionString12 {
            get {
                return ((string)(this["ScCustomsConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScCustoms;Persist Security Info=True;Us" +
            "er ID=udata")]
        public string ScCustomsConnectionString13 {
            get {
                return ((string)(this["ScCustomsConnectionString13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=127.0.0.1,1434;Initial Catalog=PvbErm;Persist Security Info=True;User" +
            " ID=sa;Password=qwerasdf12")]
        public string PvbErmConnectionString {
            get {
                return ((string)(this["PvbErmConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=ScCustoms;User ID=udata")]
        public string ScCustomsConnectionString14 {
            get {
                return ((string)(this["ScCustomsConnectionString14"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=210.51.190.51,6522;Initial Catalog=ScCustoms;Persist Security Info=Tr" +
            "ue;User ID=u_bv")]
        public string ScCustomsConnectionString15 {
            get {
                return ((string)(this["ScCustomsConnectionString15"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=CustomsBaseData;Persist Security Info=T" +
            "rue;User ID=udata;Password=udata123")]
        public string CustomsBaseDataConnectionString {
            get {
                return ((string)(this["CustomsBaseDataConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.197;Initial Catalog=CustomsBaseSystem;Persist Security Info" +
            "=True;User ID=udata")]
        public string CustomsBaseSystemConnectionString {
            get {
                return ((string)(this["CustomsBaseSystemConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.27.187;Initial Catalog=ScCustoms;Persist Security Info=True;U" +
            "ser ID=sa;Password=123")]
        public string ScCustomsConnectionString16 {
            get {
                return ((string)(this["ScCustomsConnectionString16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=ScCustoms;Persist Security Info=Tr" +
            "ue;User ID=udata;Password=Turing2019")]
        public string ScCustomsConnectionString17 {
            get {
                return ((string)(this["ScCustomsConnectionString17"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=PvWms;Persist Security Info=True;U" +
            "ser ID=udata")]
        public string ScCustomsConnectionString18 {
            get {
                return ((string)(this["ScCustomsConnectionString18"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=foricScCustoms;Persist Security In" +
            "fo=True;User ID=udata;Password=Turing2019")]
        public string foricScCustomsConnectionString {
            get {
                return ((string)(this["foricScCustomsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=ScCustoms;User ID=udata;Password=T" +
            "uring2019")]
        public string ScCustomsConnectionString19 {
            get {
                return ((string)(this["ScCustomsConnectionString19"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=foricScCustoms;User ID=udata")]
        public string foricScCustomsConnectionString1 {
            get {
                return ((string)(this["foricScCustomsConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=foricScCustoms;User ID=udata")]
        public string foricScCustomsConnectionString2 {
            get {
                return ((string)(this["foricScCustomsConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=ScCustoms;User ID=udata")]
        public string ScCustomsConnectionString20 {
            get {
                return ((string)(this["ScCustomsConnectionString20"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=ScCustoms;Persist Security Info=Tr" +
            "ue;User ID=udata")]
        public string ScCustomsConnectionString21 {
            get {
                return ((string)(this["ScCustomsConnectionString21"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.51,6522;Initial Catalog=ScCustoms;Persist Security Info=Tru" +
            "e;User ID=u_v0")]
        public string ScCustomsConnectionString22 {
            get {
                return ((string)(this["ScCustomsConnectionString22"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.51,6522;Initial Catalog=ScCustoms;Persist Security Info=Tru" +
            "e;User ID=u_v0;Password=V6e1W9MiA84t6FJ05TXCU9uRY9THg3EpT60v9X1qwMbLg895Oc")]
        public string ScCustomsConnectionString23 {
            get {
                return ((string)(this["ScCustomsConnectionString23"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=foricScCustoms;Persist Security In" +
            "fo=True;User ID=udata")]
        public string foricScCustomsConnectionString3 {
            get {
                return ((string)(this["foricScCustomsConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=foricScCustoms;Persist Security In" +
            "fo=True;User ID=udata")]
        public string foricScCustomsConnectionString4 {
            get {
                return ((string)(this["foricScCustomsConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=ScCustoms;User ID=udata")]
        public string foricScCustomsConnectionString5 {
            get {
                return ((string)(this["foricScCustomsConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=bv3crm;User ID=udata")]
        public string bv3crmConnectionString3 {
            get {
                return ((string)(this["bv3crmConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.49,6522;Initial Catalog=foricScCustoms;Persist Security Inf" +
            "o=True;User ID=u_v0")]
        public string foricScCustomsConnectionString6 {
            get {
                return ((string)(this["foricScCustomsConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=bv3crm;User ID=udata;Password=Turi" +
            "ng2019")]
        public string bv3crmConnectionString4 {
            get {
                return ((string)(this["bv3crmConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=ScCustoms;Persist Security Info=Tr" +
            "ue;User ID=udata")]
        public string PvWmsConnectionString {
            get {
                return ((string)(this["PvWmsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.51,6522;Initial Catalog=foricScCustoms;Persist Security Inf" +
            "o=True;User ID=u_v0")]
        public string foricScCustomsConnectionString7 {
            get {
                return ((string)(this["foricScCustomsConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.199,5311;Initial Catalog=foricScCustoms;Persist Security In" +
            "fo=True;User ID=udata")]
        public string foricScCustomsConnectionString8 {
            get {
                return ((string)(this["foricScCustomsConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.51,6522;Initial Catalog=foricScCustoms;Persist Security Inf" +
            "o=True;User ID=u_v0")]
        public string foricScCustomsConnectionString9 {
            get {
                return ((string)(this["foricScCustomsConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.51,6522;Initial Catalog=foricScCustoms;Persist Security Inf" +
            "o=True;User ID=u_v0")]
        public string foricScCustomsConnectionString10 {
            get {
                return ((string)(this["foricScCustomsConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.51,6522;Initial Catalog=foricScCustoms;Persist Security Inf" +
            "o=True;User ID=u_v0")]
        public string foricScCustomsConnectionString11 {
            get {
                return ((string)(this["foricScCustomsConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.51,6522;Initial Catalog=PvbCrm;Persist Security Info=True;U" +
            "ser ID=u_v0")]
        public string PvbCrmConnectionString {
            get {
                return ((string)(this["PvbCrmConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.51,6522;Initial Catalog=foricDBS;Persist Security Info=True" +
            ";User ID=u_v0;Password=V6e1W9MiA84t6FJ05TXCU9uRY9THg3EpT60v9X1qwMbLg895Oc")]
        public string foricDBSConnectionString {
            get {
                return ((string)(this["foricDBSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.51,6522;Initial Catalog=foricScCustoms;Persist Security Inf" +
            "o=True;User ID=u_v0;Password=V6e1W9MiA84t6FJ05TXCU9uRY9THg3EpT60v9X1qwMbLg895Oc")]
        public string foricScCustomsConnectionString12 {
            get {
                return ((string)(this["foricScCustomsConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.51,6522;Initial Catalog=bv3crm;Persist Security Info=True;U" +
            "ser ID=u_v0")]
        public string bv3crmConnectionString5 {
            get {
                return ((string)(this["bv3crmConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.49,6522;Initial Catalog=foricScCustoms;Persist Security Inf" +
            "o=True;User ID=u_v0")]
        public string foricScCustomsConnectionString13 {
            get {
                return ((string)(this["foricScCustomsConnectionString13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.49,6522;Initial Catalog=foricScCustoms;Persist Security Inf" +
            "o=True;User ID=u_v0")]
        public string foricScCustomsConnectionString14 {
            get {
                return ((string)(this["foricScCustomsConnectionString14"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.49,6522;Initial Catalog=foricScCustoms;Persist Security Inf" +
            "o=True;User ID=u_v0")]
        public string foricScCustomsConnectionString15 {
            get {
                return ((string)(this["foricScCustomsConnectionString15"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.10.49,6522;Initial Catalog=foricScCustoms;Persist Security Inf" +
            "o=True;User ID=u_v0;Password=hUBU376X7frzCQ5mh2OG")]
        public string foricScCustomsConnectionString16 {
            get {
                return ((string)(this["foricScCustomsConnectionString16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=221.122.108.49,6522;Initial Catalog=foricScCustoms;User ID=u_v0")]
        public string foricScCustomsConnectionString17 {
            get {
                return ((string)(this["foricScCustomsConnectionString17"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=221.122.108.49,6522;Initial Catalog=foricScCustoms;Persist Security I" +
            "nfo=True;User ID=u_v0;Password=hUBU376X7frzCQ5mh2OG")]
        public string foricScCustomsConnectionString18 {
            get {
                return ((string)(this["foricScCustomsConnectionString18"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=foricScCustoms;Persist Security Info=True;User ID=s" +
            "a;Encrypt=True;TrustServerCertificate=True")]
        public string foricScCustomsConnectionString19 {
            get {
                return ((string)(this["foricScCustomsConnectionString19"]));
            }
        }
    }
}
