<?xml version="1.0" encoding="utf-8"?><Database Name="PvbErm" Class="SqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Admins" Member="Admins">
    <Type Name="Admins">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="RealName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShowName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SelCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OriginID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PwdModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Admins_Tokens" Member="Tokens" ThisKey="ID" OtherKey="OutID" Type="Tokens" />
      <Association Name="Roles_Admins" Member="Roles" ThisKey="RoleID" OtherKey="ID" Type="Roles" IsForeignKey="true" />
      <Association Name="Staffs_Admins" Member="Staffs" ThisKey="StaffID" OtherKey="ID" Type="Staffs" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WageItems" Member="WageItems">
    <Type Name="WageItems">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsImport" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Formula" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CalcOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InputerId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="WageItems_MapsPostion" Member="MapsPostion" ThisKey="ID" OtherKey="WageItemID" Type="MapsPostion" />
    </Type>
  </Table>
  <Table Name="dbo.Advantages" Member="Advantages">
    <Type Name="Advantages">
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Manufacturers" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PartNumbers" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Applications" Member="Applications">
    <Type Name="Applications">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VoteFlowID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Context" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicantID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatorID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Applications_ApplyVoteSteps" Member="ApplyVoteSteps" ThisKey="ID" OtherKey="ApplicationID" Type="ApplyVoteSteps" />
      <Association Name="Applications_Logs_ApplyVoteSteps" Member="Logs_ApplyVoteSteps" ThisKey="ID" OtherKey="ApplicationID" Type="Logs_ApplyVoteSteps" />
    </Type>
  </Table>
  <Table Name="dbo.ApplyVoteSteps" Member="ApplyVoteSteps">
    <Type Name="ApplyVoteSteps">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplicationID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VoteStepID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsCurrent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Applications_ApplyVoteSteps" Member="Applications" ThisKey="ApplicationID" OtherKey="ID" Type="Applications" IsForeignKey="true" />
      <Association Name="VoteSteps_ApplyVoteSteps" Member="VoteSteps" ThisKey="VoteStepID" OtherKey="ID" Type="VoteSteps" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BankCards" Member="BankCards">
    <Type Name="BankCards">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Bank" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="BankAddress" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Account" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SwiftCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Staffs_BankCards" Member="Staffs" ThisKey="ID" OtherKey="ID" Type="Staffs" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Calendars" Member="Calendars">
    <Type Name="Calendars">
      <Column Name="ID" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Week" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Calendars_Logs_Attend" Member="Logs_Attend" ThisKey="ID" OtherKey="Date" Type="Logs_Attend" />
      <Association Name="Calendars_Schedules" Member="Schedules" ThisKey="ID" OtherKey="Date" Type="Schedules" />
    </Type>
  </Table>
  <Table Name="dbo.Contacts" Member="Contacts">
    <Type Name="Contacts">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QQ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Wx" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Labours" Member="Labours">
    <Type Name="Labours">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EntryCompany" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EnterpriseID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LeaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SigningTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ContractPeriod" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ContractType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SocialSecurityAccount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProbationMonths" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Staffs_Labours" Member="Staffs" ThisKey="ID" OtherKey="ID" Type="Staffs" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Leagues" Member="Leagues">
    <Type Name="Leagues">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Category" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FatherID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EnterpriseID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LeaguesPrivate" Member="LeaguesPrivate">
    <Type Name="LeaguesPrivate">
      <Column Name="AdminMainID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AdminSubID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Logs_ApplyVoteSteps" Member="Logs_ApplyVoteSteps">
    <Type Name="Logs_ApplyVoteSteps">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplicationID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VoteStepID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Applications_Logs_ApplyVoteSteps" Member="Applications" ThisKey="ApplicationID" OtherKey="ID" Type="Applications" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Logs_Attend" Member="Logs_Attend">
    <Type Name="Logs_Attend">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Calendars_Logs_Attend" Member="Calendars" ThisKey="Date" OtherKey="ID" Type="Calendars" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Logs_Errors" Member="Logs_Errors">
    <Type Name="Logs_Errors">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Page" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Codes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Stack" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Logs_Notice" Member="Logs_Notice">
    <Type Name="Logs_Notice">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Context" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Readed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReadDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MainID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Logs_StaffApprovals" Member="Logs_StaffApprovals">
    <Type Name="Logs_StaffApprovals">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ApprovalStep" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ApprovalStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoticeReportStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EnterReportStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Context" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MapsAppStaff" Member="MapsAppStaff">
    <Type Name="MapsAppStaff">
      <Column Name="ApplicationID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MapsItem" Member="MapsItem">
    <Type Name="MapsItem">
      <Column Name="WageItemID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MapsLeague" Member="MapsLeague">
    <Type Name="MapsLeague">
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LeagueID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MapsPostion" Member="MapsPostion">
    <Type Name="MapsPostion">
      <Column Name="PostionID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WageItemID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="WageItems_MapsPostion" Member="WageItems" ThisKey="WageItemID" OtherKey="ID" Type="WageItems" IsForeignKey="true" />
      <Association Name="Postions_MapsPostion" Member="Postions" ThisKey="PostionID" OtherKey="ID" Type="Postions" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MapsRole" Member="MapsRole">
    <Type Name="MapsRole">
      <Column Name="MenuID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Roles_MapsRole" Member="Roles" ThisKey="RoleID" OtherKey="ID" Type="Roles" IsForeignKey="true" />
      <Association Name="Menus_MapsRole" Member="Menus" ThisKey="MenuID" OtherKey="ID" Type="Menus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MapsRoleCompose" Member="MapsRoleCompose">
    <Type Name="MapsRoleCompose">
      <Column Name="RoleID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChildID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MapsWageItem" Member="MapsWageItem">
    <Type Name="MapsWageItem">
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WageItemID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DefaultValue" Type="System.Decimal" DbType="Decimal(18,5)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MapsWareHouse" Member="MapsWareHouse">
    <Type Name="MapsWareHouse">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WareHouseID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ConsigneeID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Oplogs" Member="Oplogs">
    <Type Name="Oplogs">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Sys" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Operation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Particles" Member="Particles">
    <Type Name="Particles">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UrlCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="Context" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ParticleSettings" Member="ParticleSettings">
    <Type Name="ParticleSettings">
      <Column Name="RoleID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UrlCode" Type="System.String" DbType="VarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="Context" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Pasts_AdminPassword" Member="Pasts_AdminPassword">
    <Type Name="Pasts_AdminPassword">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Pasts_Attend" Member="Pasts_Attend">
    <Type Name="Pasts_Attend">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="AmOrPm" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SchedulingID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InFact" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsLater" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsEarly" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OnWorkRemedy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OffWorkRemedy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pasts_MapsWageItem" Member="Pasts_MapsWageItem">
    <Type Name="Pasts_MapsWageItem">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WageItemID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultValue" Type="System.Decimal" DbType="Decimal(18,5)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Pasts_WageItem" Member="Pasts_WageItem">
    <Type Name="Pasts_WageItem">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WorkCityID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EnterpriseID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Accumulative" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PayBills" Member="PayBills">
    <Type Name="PayBills">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClosedData" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateIndex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreaetDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EnterpriseID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PostionID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="PayBills_PayItems" Member="PayItems" ThisKey="ID" OtherKey="PayID" Type="PayItems" />
      <Association Name="Staffs_PayBills" Member="Staffs" ThisKey="StaffID" OtherKey="ID" Type="Staffs" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PayItems" Member="PayItems">
    <Type Name="PayItems">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PayID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="DateIndex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WageItemFormula" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ActualFormula" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateAdminID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PayBills_PayItems" Member="PayBills" ThisKey="PayID" OtherKey="ID" Type="PayBills" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PersonalFamilyMembers" Member="PersonalFamilyMembers">
    <Type Name="PersonalFamilyMembers">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Relation" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Company" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PersonalRates" Member="PersonalRates">
    <Type Name="PersonalRates">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Levels" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BeginAmount" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="EndAmount" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="Deduction" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Personals" Member="Personals">
    <Type Name="Personals">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDCard" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="NativePlace" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="HomeAddress" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PassAddress" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Volk" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PoliticalOutlook" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Height" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Blood" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Education" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GraduatInstitutions" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Major" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsMarry" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BeginWorkDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Healthy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GraduationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EmergencyContact" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmergencyMobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LanguageLevel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ComputerLevel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SelfEvaluation" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Treatment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PositionName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Association Name="Staffs_Personals" Member="Staffs" ThisKey="ID" OtherKey="ID" Type="Staffs" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PersonalWorkExperiences" Member="PersonalWorkExperiences">
    <Type Name="PersonalWorkExperiences">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Company" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Salary" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="LeaveReason" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PositionsAc" Member="PositionsAc">
    <Type Name="PositionsAc">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RegionID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatorID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifyID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Postions" Member="Postions">
    <Type Name="Postions">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Postions_MapsPostion" Member="MapsPostion" ThisKey="ID" OtherKey="PostionID" Type="MapsPostion" />
      <Association Name="Postions_Staffs" Member="Staffs" ThisKey="ID" OtherKey="PostionID" Type="Staffs" />
    </Type>
  </Table>
  <Table Name="dbo.RegionsAc" Member="RegionsAc">
    <Type Name="RegionsAc">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FatherID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatorID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifyID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Roles">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Roles_Admins" Member="Admins" ThisKey="ID" OtherKey="RoleID" Type="Admins" />
      <Association Name="Roles_MapsRole" Member="MapsRole" ThisKey="ID" OtherKey="RoleID" Type="MapsRole" />
    </Type>
  </Table>
  <Table Name="dbo.Schedules" Member="Schedules">
    <Type Name="Schedules">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatorID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifyID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Schedules_SchedulesPrivate" Member="SchedulesPrivate" ThisKey="ID" OtherKey="ID" Type="SchedulesPrivate" Cardinality="One" />
      <Association Name="Schedules_SchedulesPublic" Member="SchedulesPublic" ThisKey="ID" OtherKey="ID" Type="SchedulesPublic" Cardinality="One" />
      <Association Name="Calendars_Schedules" Member="Calendars" ThisKey="Date" OtherKey="ID" Type="Calendars" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SchedulesPrivate" Member="SchedulesPrivate">
    <Type Name="SchedulesPrivate">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplicationID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AmOrPm" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OnWorkRemedy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OffWorkRemedy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Schedules_SchedulesPrivate" Member="Schedules" ThisKey="ID" OtherKey="ID" Type="Schedules" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SchedulesPublic" Member="SchedulesPublic">
    <Type Name="SchedulesPublic">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Method" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[From]" Member="From" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegionID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PostionID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SalaryMultiple" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="ShiftID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SchedulingID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Schedules_SchedulesPublic" Member="Schedules" ThisKey="ID" OtherKey="ID" Type="Schedules" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Schedulings" Member="Schedulings">
    <Type Name="Schedulings">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PostionID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AmStartTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="AmEndTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="PmStartTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="PmEndTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="DomainValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsMain" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SealCertificates" Member="SealCertificates">
    <Type Name="SealCertificates">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EnterpriseID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProcessingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Settings">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DataType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ShiftStaffs" Member="ShiftStaffs">
    <Type Name="ShiftStaffs">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ShiftSchedule" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ShiftRules" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NextSchedulingID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatorID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifyID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Staffs" Member="Staffs">
    <Type Name="Staffs">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SelCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DyjCompanyCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DyjDepartmentCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DyjCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WorkCity" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LeagueID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PostionID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DepartmentCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PostionCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AssessmentMethod" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AssessmentTime" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegionID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SchedulingID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Staffs_Admins" Member="Admins" ThisKey="ID" OtherKey="StaffID" Type="Admins" />
      <Association Name="Staffs_BankCards" Member="BankCards" ThisKey="ID" OtherKey="ID" Type="BankCards" Cardinality="One" />
      <Association Name="Staffs_Labours" Member="Labours" ThisKey="ID" OtherKey="ID" Type="Labours" Cardinality="One" />
      <Association Name="Staffs_PayBills" Member="PayBills" ThisKey="ID" OtherKey="StaffID" Type="PayBills" />
      <Association Name="Staffs_Personals" Member="Personals" ThisKey="ID" OtherKey="ID" Type="Personals" Cardinality="One" />
      <Association Name="Postions_Staffs" Member="Postions" ThisKey="PostionID" OtherKey="ID" Type="Postions" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StaffWxs" Member="StaffWxs">
    <Type Name="StaffWxs">
      <Column Name="UnionID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OpenID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nickname" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Sex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HeadImgurl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Temp_DyjAttend" Member="Temp_DyjAttend">
    <Type Name="Temp_DyjAttend">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DyjID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BeginIP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EndIP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tokens" Member="Tokens">
    <Type Name="Tokens">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OutID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Admins_Tokens" Member="Admins" ThisKey="OutID" OtherKey="ID" Type="Admins" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VoteFlows" Member="VoteFlows">
    <Type Name="VoteFlows">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatorID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifyID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="VoteFlows_VoteSteps" Member="VoteSteps" ThisKey="ID" OtherKey="VoteFlowID" Type="VoteSteps" />
    </Type>
  </Table>
  <Table Name="dbo.VoteSteps" Member="VoteSteps">
    <Type Name="VoteSteps">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VoteFlowID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OrderIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PositionID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Uri" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Association Name="VoteSteps_ApplyVoteSteps" Member="ApplyVoteSteps" ThisKey="ID" OtherKey="VoteStepID" Type="ApplyVoteSteps" />
      <Association Name="VoteFlows_VoteSteps" Member="VoteFlows" ThisKey="VoteFlowID" OtherKey="ID" Type="VoteFlows" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdminAdvantagesTopView" Member="AdminAdvantagesTopView">
    <Type Name="AdminAdvantagesTopView">
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Manufacturers" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PartNumbers" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WorkCitiesTopView" Member="WorkCitiesTopView">
    <Type Name="WorkCitiesTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AdminsBussinessTopView" Member="AdminsBussinessTopView">
    <Type Name="AdminsBussinessTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="RealName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SelCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RoleID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="bussiness" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AdminsInfoTopView" Member="AdminsInfoTopView">
    <Type Name="AdminsInfoTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="RealName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SelCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDCard" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="NativePlace" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="HomeAddress" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PassAddress" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Volk" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PoliticalOutlook" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Height" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Blood" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Education" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GraduatInstitutions" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Major" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsMarry" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdminsTopView" Member="AdminsTopView">
    <Type Name="AdminsTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="RealName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SelCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RoleID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RoleStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OriginID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdminsWmsView" Member="AdminsWmsView">
    <Type Name="AdminsWmsView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="RealName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SelCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="bussiness" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ApprovalsStatisticsView" Member="ApprovalsStatisticsView">
    <Type Name="ApprovalsStatisticsView">
      <Column Name="ApplicationID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VoteFlowID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Context" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicantID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatorID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VoteFlowName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VoteFlowsID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ApplyVoteStepsID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VoteStepID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ApproveID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VoteStepName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PositionID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Uri" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BomQuotesTopView" Member="BomQuotesTopView">
    <Type Name="BomQuotesTopView">
      <Column Name="PartNumber" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Manufacturer" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PackageCase" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Supplier" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Packaging" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sign" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Moq" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CompaniesTopView" Member="CompaniesTopView">
    <Type Name="CompaniesTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Range" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="District" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LogsAttendTopView" Member="LogsAttendTopView">
    <Type Name="LogsAttendTopView">
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Am" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Pm" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MapsRoleComposeTopView" Member="MapsRoleComposeTopView">
    <Type Name="MapsRoleComposeTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChildID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MapsWareHouseView" Member="MapsWareHouseView">
    <Type Name="MapsWareHouseView">
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WareHouseID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PastsAttendTopView" Member="PastsAttendTopView">
    <Type Name="PastsAttendTopView">
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AmOrPm" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SchedulingID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InFact" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsLater" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsEarly" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OnWorkRemedy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OffWorkRemedy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StaffsTopView" Member="StaffsTopView">
    <Type Name="StaffsTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DyjCompanyCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DyjDepartmentCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DyjCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WorkCity" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubsWarehousesTopView" Member="SubsWarehousesTopView">
    <Type Name="SubsWarehousesTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EnterpriseID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="WsCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Postzip" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DyjCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="District" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Corporation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Uscc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RegAddress" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ConsinStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WarehousePlatesTopView" Member="WarehousePlatesTopView">
    <Type Name="WarehousePlatesTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Postzip" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EnterpriseID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WarehouseName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="WarehouseAddress" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="WsCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WarehouseStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Vacations" Member="Vacations">
    <Type Name="Vacations">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="Lefts" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Menus" Member="Menus">
    <Type Name="Menus">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FatherID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RightUrl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IconUrl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="FirstUrl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="LogoUrl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="HelpUrl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="OrderIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsLocal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Menus_MapsRole" Member="MapsRole" ThisKey="ID" OtherKey="MenuID" Type="MapsRole" />
    </Type>
  </Table>
  <Function Name="dbo.P_CalcWageByPayId" Method="P_CalcWageByPayId">
    <Parameter Name="payId" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="adminId" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.P_ReplaceMethodByFormula" Method="P_ReplaceMethodByFormula">
    <Parameter Name="str" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="dateIndex" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="staffId" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="result" Type="System.String" DbType="NVarChar(500)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.P_CreatePKey" Method="P_CreatePKey">
    <Parameter Name="NAME" Parameter="nAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LENGTH" Parameter="lENGTH" Type="System.Int32" DbType="Int" />
    <Parameter Name="PRIMARYKEYTYPE" Parameter="pRIMARYKEYTYPE" Type="System.Int32" DbType="Int" />
    <Parameter Name="Type" Parameter="type" Type="System.Int32" DbType="Int" />
    <Parameter Name="VAL" Parameter="vAL" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.P_ImportWageData" Method="P_ImportWageData">
    <Parameter Name="json" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="dateIndex" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="adminId" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="error_msg" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="P_ImportWageDataResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>