//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wl.HistoryImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Control_ApproveRecord
    {
        public string ID { get; set; }
        public string OrderID { get; set; }
        public int ApproveResult { get; set; }
        public string Approver { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
