//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wl.HistoryImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Download_History
    {
        public string ID { get; set; }
        public string UserID { get; set; }
        public string MemberCode { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> DownloadTime { get; set; }
        public Nullable<bool> Success { get; set; }
        public string Error { get; set; }
    }
}
