//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wl.HistoryImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Finance_Account
    {
        public string ID { get; set; }
        public string VaultID { get; set; }
        public string AccountName { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string BankAccount { get; set; }
        public string BankCode { get; set; }
        public decimal Balance { get; set; }
        public int Currency { get; set; }
        public string Remark { get; set; }
        public Nullable<int> RecordStatus { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Updator { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
