//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wl.HistoryImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Icgoo_Declare_Default
    {
        public string id { get; set; }
        public string PartNo { get; set; }
        public string Brand { get; set; }
        public string Origin { get; set; }
        public Nullable<decimal> Custom_Rate { get; set; }
        public Nullable<decimal> Add_Rate { get; set; }
        public string Procduct_Name { get; set; }
        public Nullable<int> Type { get; set; }
        public string HS_Code { get; set; }
        public string Tax_Code { get; set; }
        public string Elements { get; set; }
        public string FirstLegalUnit { get; set; }
        public string SecondLegalUnit { get; set; }
        public Nullable<bool> IsInspection { get; set; }
        public Nullable<decimal> InspectionFee { get; set; }
        public string CIQCode { get; set; }
        public string Category { get; set; }
        public System.DateTime Createtime { get; set; }
        public System.DateTime Updatetime { get; set; }
    }
}
