//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wl.HistoryImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Member_Products
    {
        public string ID { get; set; }
        public string MemberID { get; set; }
        public string Model { get; set; }
        public string Brand { get; set; }
        public string BatchNo { get; set; }
        public string ProductName { get; set; }
        public Nullable<bool> IsInspection { get; set; }
        public Nullable<decimal> TariffRate { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string CustomsCode { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<System.DateTime> DeclarationDate { get; set; }
    }
}
