//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wl.HistoryImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Order
    {
        public string ID { get; set; }
        public string MemberID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<int> OrderCategory { get; set; }
        public Nullable<int> InvoicingStatus { get; set; }
        public string SalesManID { get; set; }
        public string MerchandiserID { get; set; }
        public string AccountStatement { get; set; }
        public string CancelReason { get; set; }
        public Nullable<int> RecordStatus { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Updator { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public int SerialNo { get; set; }
        public int GetAllMoney { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<System.DateTime> ProfitDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> IsLocal { get; set; }
    }
}
