//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wl.HistoryImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Order_Attachments
    {
        public string ID { get; set; }
        public string OrderID { get; set; }
        public Nullable<int> AttachmentType { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentAddress { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public Nullable<bool> IsCheck { get; set; }
        public Nullable<int> CheckStatus { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Creator { get; set; }
        public string MD5 { get; set; }
    }
}
