//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wl.HistoryImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Order_Model_Default
    {
        public string ID { get; set; }
        public string DeclareProductName { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string CustomsCode { get; set; }
        public string CIQCode { get; set; }
        public Nullable<bool> IsInspection { get; set; }
        public Nullable<decimal> InspectionFee { get; set; }
        public Nullable<decimal> TariffRate { get; set; }
        public Nullable<decimal> ValueAddedTaxRate { get; set; }
        public string Elements { get; set; }
        public string Manufacturer { get; set; }
        public string Description { get; set; }
        public string FirstLegalUnit { get; set; }
        public string SecondLegalUnit { get; set; }
        public string TaxCode { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
