//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wl.HistoryImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Tax_New
    {
        public int id { get; set; }
        public string TaxCode { get; set; }
        public string TaxName { get; set; }
        public string Desp { get; set; }
        public string KeyWords { get; set; }
        public Nullable<int> IsElectronic { get; set; }
    }
}
