<?xml version="1.0" encoding="utf-8"?><Database Name="foricScCustoms" Class="SqlFinanceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.30.10.49,6522;Initial Catalog=foricScCustoms;Persist Security Info=True;User ID=u_v0" SettingsObjectName="Layer.Data.Properties.Settings" SettingsPropertyName="foricScCustomsConnectionString6" Provider="System.Data.SqlClient" />
  <Table Name="dbo.InvoiceWaybills" Member="InvoiceWaybills">
    <Type Name="InvoiceWaybills">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InvoiceNoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WaybillCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="InvoiceNotices_InvoiceWaybills" Member="InvoiceNotices" ThisKey="InvoiceNoticeID" OtherKey="ID" Type="InvoiceNotices" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentNoticeItems" Member="PaymentNoticeItems">
    <Type Name="PaymentNoticeItems">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PaymentNoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FeeType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="PaymentNotices_PaymentNoticeItems" Member="PaymentNotices" ThisKey="PaymentNoticeID" OtherKey="ID" Type="PaymentNotices" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentApplies" Member="PaymentApplies">
    <Type Name="PaymentApplies">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApplierID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApproverID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FeeType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FeeDesc" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PayeeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BankAccount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PayDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PayType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ApplyStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentApplyLogs" Member="PaymentApplyLogs">
    <Type Name="PaymentApplyLogs">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PaymentApplyID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentApplyStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentNoticeFiles" Member="PaymentNoticeFiles">
    <Type Name="PaymentNoticeFiles">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PaymentNoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="FileType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileFormat" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Association Name="PaymentNotices_PaymentNoticeFiles" Member="PaymentNotices" ThisKey="PaymentNoticeID" OtherKey="ID" Type="PaymentNotices" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FinanceAccountFlows" Member="FinanceAccountFlows">
    <Type Name="FinanceAccountFlows">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SeqNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SourceID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FinanceVaultID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FinanceAccountID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FeeType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AccountBalance" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="FinanceVaults_FinanceAccountFlows" Member="FinanceVaults" ThisKey="FinanceVaultID" OtherKey="ID" Type="FinanceVaults" IsForeignKey="true" />
      <Association Name="FinanceAccounts_FinanceAccountFlows" Member="FinanceAccounts" ThisKey="FinanceAccountID" OtherKey="ID" Type="FinanceAccounts" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceNoticeLogs" Member="InvoiceNoticeLogs">
    <Type Name="InvoiceNoticeLogs">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InvoiceNoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SwapLimitCountries" Member="SwapLimitCountries">
    <Type Name="SwapLimitCountries">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BankID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SwapBanks" Member="SwapBanks">
    <Type Name="SwapBanks">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SwapLimitCountryLogs" Member="SwapLimitCountryLogs">
    <Type Name="SwapLimitCountryLogs">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BankID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(550) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ExpressKdds" Member="ExpressKdds">
    <Type Name="ExpressKdds">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SenderComp" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sender" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SenderMobile" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SenderAddress" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ReceiverComp" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Receiver" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ReveiveMobile" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ReveiveAddress" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ExpressCompanyID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ExpressTypeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PayType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WaybillCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SwapNoticeItems" Member="SwapNoticeItems">
    <Type Name="SwapNoticeItems">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SwapNoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DecHeadID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomizeAmount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="IsOld" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SwapNotices_SwapNoticeItems" Member="SwapNotices" ThisKey="SwapNoticeID" OtherKey="ID" Type="SwapNotices" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceNoticeFiles" Member="InvoiceNoticeFiles">
    <Type Name="InvoiceNoticeFiles">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InvoiceNoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="FileType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileFormat" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CostApplyFiles" Member="CostApplyFiles">
    <Type Name="CostApplyFiles">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CostApplyID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="FileType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileFormat" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CostApplyApiLogs" Member="CostApplyApiLogs">
    <Type Name="CostApplyApiLogs">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BatchID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CostApplyID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PaymentNoticeID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="RequestContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ResponseContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VouchersStatisticsView" Member="VouchersStatisticsView">
    <Type Name="VouchersStatisticsView">
      <Column Name="ReceivableID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MainOrderID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Catalog" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LeftPrice" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="RightPrice" Type="System.Decimal" DbType="Decimal(38,7)" CanBeNull="true" />
      <Column Name="ReducePrice" Type="System.Decimal" DbType="Decimal(38,7)" CanBeNull="true" />
      <Column Name="ApplicationID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReceivedsStatisticsView" Member="ReceivedsStatisticsView">
    <Type Name="ReceivedsStatisticsView">
      <Column Name="ReceivedID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReceivableID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Business" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Catalog" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Payer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PayerName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Payee" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PayeeName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AccountType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SettlementCurrency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TinyID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CostApplyPayees" Member="CostApplyPayees">
    <Type Name="CostApplyPayees">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PayeeName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PayeeAccount" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PayeeBank" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CostApplyLogs" Member="CostApplyLogs">
    <Type Name="CostApplyLogs">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CostApplyID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CurrentCostStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NextCostStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WsOrderTopView" Member="WsOrderTopView">
    <Type Name="WsOrderTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PayeeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SupplierID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SettlementCurrency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="inBeneficiaryID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsPayCharge" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InWayBillID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="inCurrency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InConditions" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="outBeneficiaryID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsReciveCharge" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OutWayBillID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OutConditions" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="outCurrency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MainStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RemittanceStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ChineseName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EnglishName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaySupplierInfos" Member="PaySupplierInfos">
    <Type Name="PaySupplierInfos">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DecHeadID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SupplierName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PayType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FinanceVouchers" Member="FinanceVouchers">
    <Type Name="FinanceVouchers">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UseAdminID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UseTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SwapNoticeReceiptUses" Member="SwapNoticeReceiptUses">
    <Type Name="SwapNoticeReceiptUses">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SourceID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderReceiptID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderReceiptAmount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="SwapNoticeID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SwapNoticeAmountCNY" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SwapNoticeReceiptUseLogs" Member="SwapNoticeReceiptUseLogs">
    <Type Name="SwapNoticeReceiptUseLogs">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SwapNoticeReceiptUseID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderReceiptID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderReceiptAmount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="SwapNoticeID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SwapNoticeAmountCNY" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SwapNoticesLogs" Member="SwapNoticesLogs">
    <Type Name="SwapNoticesLogs">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SwapNoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FinancePaymentOperators" Member="FinancePaymentOperators">
    <Type Name="FinancePaymentOperators">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UnSwapDecHeadListBaseView" Member="UnSwapDecHeadListBaseView">
    <Type Name="UnSwapDecHeadListBaseView">
      <Column Name="DecHeadID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContrNo" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="EntryId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OwnerName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SwapStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CusDecStatus" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="ClientType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsOverDate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsHasLimitArea" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DecHeadAmount" Type="System.Decimal" DbType="Decimal(38,4) NOT NULL" CanBeNull="false" />
      <Column Name="OrderAmount" Type="System.Decimal" DbType="Decimal(38,4) NOT NULL" CanBeNull="false" />
      <Column Name="IsApplyPayExchange" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsPrePayExchange" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Receivables" Member="Receivables">
    <Type Name="Receivables">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FinanceReceiptID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CNYAmount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="MatchStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReceivablesMap" Member="ReceivablesMap">
    <Type Name="ReceivablesMap">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReceivableID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GoodsFee" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="TaxFee" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="AgencyFee" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="IncidentalFee" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PvFinanceAccountCatalogs" Member="PvFinanceAccountCatalogs">
    <Type Name="PvFinanceAccountCatalogs">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FatherID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CreatorID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifierID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FinanceVaults" Member="FinanceVaults">
    <Type Name="FinanceVaults">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Leader" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BigWinVaultID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="FinanceVaults_FinanceAccountFlows" Member="FinanceAccountFlows" ThisKey="ID" OtherKey="FinanceVaultID" Type="FinanceAccountFlows" />
      <Association Name="FinanceVaults_FinanceAccounts" Member="FinanceAccounts" ThisKey="ID" OtherKey="FinanceVaultID" Type="FinanceAccounts" />
      <Association Name="FinanceVaults_FinancePayments" Member="FinancePayments" ThisKey="ID" OtherKey="FinanceVaultID" Type="FinancePayments" />
      <Association Name="FinanceVaults_FinanceReceipts" Member="FinanceReceipts" ThisKey="ID" OtherKey="FinanceVaultID" Type="FinanceReceipts" />
    </Type>
  </Table>
  <Table Name="dbo.PayeeRightsTopView" Member="PayeeRightsTopView">
    <Type Name="PayeeRightsTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LeftID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(22,10) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReviewerID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FlowFormCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PayeeLeftsTopView" Member="PayeeLeftsTopView">
    <Type Name="PayeeLeftsTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Source" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PayerID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PayeeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Conduct" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(22,10) NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(22,10) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CutDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CutDateIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoticeID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FormID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WaybillCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VoucherID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PayerName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FinanceAccounts" Member="FinanceAccounts">
    <Type Name="FinanceAccounts">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FinanceVaultID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BankAccount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="BankAddress" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SwiftCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CustomizedCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsCash" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccountType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminInchargeID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BigWinAccountID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Source" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsVirtual" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="FinanceAccounts_FinanceAccountFlows" Member="FinanceAccountFlows" ThisKey="ID" OtherKey="FinanceAccountID" Type="FinanceAccountFlows" />
      <Association Name="FinanceAccounts_FinancePayments" Member="FinancePayments" ThisKey="ID" OtherKey="FinanceAccountID" Type="FinancePayments" />
      <Association Name="FinanceAccounts_FinanceReceipts" Member="FinanceReceipts" ThisKey="ID" OtherKey="FinanceAccountID" Type="FinanceReceipts" />
      <Association Name="FinanceVaults_FinanceAccounts" Member="FinanceVaults" ThisKey="FinanceVaultID" OtherKey="ID" Type="FinanceVaults" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceNoticeItems" Member="InvoiceNoticeItems">
    <Type Name="InvoiceNoticeItems">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InvoiceNoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="OrderItemID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Difference" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceCode" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="InvoiceNo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="InvoiceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="InvoiceNotices_InvoiceNoticeItems" Member="InvoiceNotices" ThisKey="InvoiceNoticeID" OtherKey="ID" Type="InvoiceNotices" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaxManageMap" Member="TaxManageMap">
    <Type Name="TaxManageMap">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TaxManageID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceNoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceResults" Member="InvoiceResults">
    <Type Name="InvoiceResults">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RtnCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="resultCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="invoicefalseCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="invoiceTypeName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="invoiceTypeCode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="checkDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="checkNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="invoiceDataCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="invoiceNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="billingTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="purchaserName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="taxpayerNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="taxDiskCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="taxpayerAddressOrId" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="taxpayerBankAccount" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="salesName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="salesTaxpayerNum" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="salesTaxpayerAddress" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="salesTaxpayerBankAccount" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="totalAmount" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="totalTaxNum" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="totalTaxSum" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="invoiceRemarks" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="goodsClerk" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="checkCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="voidMark" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="isBillMark" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="tollSign" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="tollSignName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="resultMsg" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="invoiceName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaxMapJobLog" Member="TaxMapJobLog">
    <Type Name="TaxMapJobLog">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SchedulerTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NextTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Exception" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaxManage" Member="TaxManage">
    <Type Name="TaxManage">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InvoiceCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellsName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="VaildAmount" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="ConfrimDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AuthenticationMonth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsVaild" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InvoiceDetailID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BusinessType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaxMap" Member="TaxMap">
    <Type Name="TaxMap">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InvoiceNoticeID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsMapped" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ApiStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceResultDetails" Member="InvoiceResultDetails">
    <Type Name="InvoiceResultDetails">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InvoiceResultID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lineNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="goodserviceName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="model" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="number" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="sum" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="taxRate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tax" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="isBillLine" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="zeroTaxRateSign" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="zeroTaxRateSignName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StorageFeeReport" Member="StorageFeeReport">
    <Type Name="StorageFeeReport">
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Business" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Catalog" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="Price1" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="LeftPrice" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="RightPrice" Type="System.Decimal" DbType="Decimal(38,7)" CanBeNull="true" />
      <Column Name="LeftDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RealName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="payCompanyName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="recCompanyName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Currency" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReceiptNotices" Member="ReceiptNotices">
    <Type Name="ReceiptNotices">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AvailableAmount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="ClearAmount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="FinanceReceipts_ReceiptNotices" Member="FinanceReceipts" ThisKey="ID" OtherKey="ID" Type="FinanceReceipts" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentNotices" Member="PaymentNotices">
    <Type Name="PaymentNotices">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SeqNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PayerID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PaymentApplyID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PayExchangeApplyID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FinanceVaultID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FinanceAccountID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FeeType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FeeDesc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PayeeName" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="BankAccount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="USDAmount" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ExchangeRate" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="PayDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PayType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CostApplyID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Poundage" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="SeqNoPoundage" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RefundApplyID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="PaymentNotices_PaymentNoticeItems" Member="PaymentNoticeItems" ThisKey="ID" OtherKey="PaymentNoticeID" Type="PaymentNoticeItems" />
      <Association Name="PaymentNotices_PaymentNoticeFiles" Member="PaymentNoticeFiles" ThisKey="ID" OtherKey="PaymentNoticeID" Type="PaymentNoticeFiles" />
    </Type>
  </Table>
  <Table Name="dbo.RefundApply" Member="RefundApply">
    <Type Name="RefundApply">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PayeeAccountID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FinanceReceiptID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ExchangeRate" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApplyStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ExpireOrders" Member="ExpireOrders">
    <Type Name="ExpireOrders">
      <Column Name="ID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="ExpireDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CostApplies" Member="CostApplies">
    <Type Name="CostApplies">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CostType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FeeType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FeeDesc" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PayeeName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PayeeAccount" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PayeeBank" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PayeeAccountID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CostStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PayTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="BillNo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MoneyType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CashType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaperNotesStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DyjID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DyjCheckID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CostApplyItems" Member="CostApplyItems">
    <Type Name="CostApplyItems">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CostApplyID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FeeType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="FeeDesc" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DyjID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DyjFeeType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceNoticeXmlItems" Member="InvoiceNoticeXmlItems">
    <Type Name="InvoiceNoticeXmlItems">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InvoiceNoticeXmlID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceNoticeItemID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Xh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Spmc" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Ggxh" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Jldw" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Spbm" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Qyspbm" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Syyhzcbz" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lslbz" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Yhzcsm" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dj" Type="System.Decimal" DbType="Decimal(21,10) NOT NULL" CanBeNull="false" />
      <Column Name="Sl" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="Je" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Slv" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Se" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Kce" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="InvoiceNoticeXmls_InvoiceNoticeXmlItems" Member="InvoiceNoticeXmls" ThisKey="InvoiceNoticeXmlID" OtherKey="ID" Type="InvoiceNoticeXmls" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceDateTopView" Member="InvoiceDateTopView">
    <Type Name="InvoiceDateTopView">
      <Column Name="InvoiceNoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceNotices" Member="InvoiceNotices">
    <Type Name="InvoiceNotices">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplyID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientInvoiceID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceTaxRate" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="BankAccount" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MailName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="MailMobile" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MailAddress" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IsExStock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VoucherNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AmountLimit" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Association Name="InvoiceNotices_InvoiceWaybills" Member="InvoiceWaybills" ThisKey="ID" OtherKey="InvoiceNoticeID" Type="InvoiceWaybills" />
      <Association Name="InvoiceNotices_InvoiceNoticeItems" Member="InvoiceNoticeItems" ThisKey="ID" OtherKey="InvoiceNoticeID" Type="InvoiceNoticeItems" />
      <Association Name="InvoiceNotices_InvoiceNoticeXmls" Member="InvoiceNoticeXmls" ThisKey="ID" OtherKey="InvoiceNoticeID" Type="InvoiceNoticeXmls" />
    </Type>
  </Table>
  <Table Name="dbo.OrderReceipts" Member="OrderReceipts">
    <Type Name="OrderReceipts">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FinanceReceiptID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FeeSourceID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FeeType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ReImport" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderReceiptImportItems" Member="OrderReceiptImportItems">
    <Type Name="OrderReceiptImportItems">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ImportID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FinanceRepID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Seq" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="USD" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="RMB" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="DeclareRate" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FinancePayments" Member="FinancePayments">
    <Type Name="FinancePayments">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SeqNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PayeeName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="BankAccount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PayerID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FeeType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FinanceVaultID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FinanceAccountID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ExchangeRate" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="PayType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PayDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsPaperInvoiceUpload" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FinPCreSta" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FinPCreWord" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FinPCreNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RequestID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="FinanceAccounts_FinancePayments" Member="FinanceAccounts" ThisKey="FinanceAccountID" OtherKey="ID" Type="FinanceAccounts" IsForeignKey="true" />
      <Association Name="FinanceVaults_FinancePayments" Member="FinanceVaults" ThisKey="FinanceVaultID" OtherKey="ID" Type="FinanceVaults" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FinanceReceipts" Member="FinanceReceipts">
    <Type Name="FinanceReceipts">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SeqNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Payer" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="FeeType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="FinanceVaultID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FinanceAccountID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccountProperty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DyjID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GoodsCreStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GoodsCreWord" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GoodsCreNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RequestID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="FinanceReceipts_ReceiptNotices" Member="ReceiptNotices" ThisKey="ID" OtherKey="ID" Type="ReceiptNotices" Cardinality="One" />
      <Association Name="FinanceAccounts_FinanceReceipts" Member="FinanceAccounts" ThisKey="FinanceAccountID" OtherKey="ID" Type="FinanceAccounts" IsForeignKey="true" />
      <Association Name="FinanceVaults_FinanceReceipts" Member="FinanceVaults" ThisKey="FinanceVaultID" OtherKey="ID" Type="FinanceVaults" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FundTransferApplies" Member="FundTransferApplies">
    <Type Name="FundTransferApplies">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FromSeqNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OutAccountID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OutSeqNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OutAmount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="OutCurrency" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="InAccountID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InSeqNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InAmount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="InCurrency" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="DiscountInterest" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="Poundage" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="PoundageSeqNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FeeType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ApplyStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QRCodeFee" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FundTranCreSta" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FundTranCreWord" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FundTranCreNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RequestID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceNoticeXmls" Member="InvoiceNoticeXmls">
    <Type Name="InvoiceNoticeXmls">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InvoiceNoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Djh" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Gfmc" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gfsh" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gfyhzh" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gfdzdh" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Bz" Type="System.String" DbType="VarChar(240)" CanBeNull="true" />
      <Column Name="Fhr" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Skr" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Spbmbbh" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Hsbz" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="InvoiceCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="InvoiceNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="InvoiceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InCreSta" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InCreWord" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InCreNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RequestID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="InvoiceNoticeXmls_InvoiceNoticeXmlItems" Member="InvoiceNoticeXmlItems" ThisKey="ID" OtherKey="InvoiceNoticeXmlID" Type="InvoiceNoticeXmlItems" />
      <Association Name="InvoiceNotices_InvoiceNoticeXmls" Member="InvoiceNotices" ThisKey="InvoiceNoticeID" OtherKey="ID" Type="InvoiceNotices" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SwapNotices" Member="SwapNotices">
    <Type Name="SwapNotices">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="ExchangeRate" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="TotalAmountCNY" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="OutFinanceAccountID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InFinanceAccountID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MidFinanceAccountID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Poundage" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="RealTimeExchangeRate" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="ConsignorCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsReceiptUseOut" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="uid" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RequestID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SwapCreSta" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SwapCreWord" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SwapCreNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="SwapNotices_SwapNoticeItems" Member="SwapNoticeItems" ThisKey="ID" OtherKey="SwapNoticeID" Type="SwapNoticeItems" />
    </Type>
  </Table>
  <Table Name="dbo.OrderReceiptImport" Member="OrderReceiptImport">
    <Type Name="OrderReceiptImport">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RequestID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OrderReceiptID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PreMoney" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Diff" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="GoodsMoney" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AddTax" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Tariff" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="ExciseTax" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Agency" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="ReCreWord" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReCreNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MKDeclareImport" Member="MKDeclareImport">
    <Type Name="MKDeclareImport">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RequestID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TemplateCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SchemeCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeclareDate" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tian" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Jinkou" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Huokuan" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Yunbaoza" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Guanshui" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="GuanshuiShijiao" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Xiaofeishui" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="XiaofeishuiShijiao" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Shui" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Jinxiangshui" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="HuiduiSanfang" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Sanfang" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="HuiduiWofang" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Huilv" Type="System.Decimal" DbType="Decimal(18,6) NOT NULL" CanBeNull="false" />
      <Column Name="YingfuSanfang" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Wuliufang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="YingfuWofang" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="PingzhengZi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PingzhengHao" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MoneyOrders" Member="MoneyOrders">
    <Type Name="MoneyOrders">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BankCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="BankNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(22,10) NOT NULL" CanBeNull="false" />
      <Column Name="PayerAccountID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PayeeAccountID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsTransfer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsMoney" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Nature" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExchangeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExchangePrice" Type="System.Decimal" DbType="Decimal(22,10)" CanBeNull="true" />
      <Column Name="AcceptedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Endorser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BillStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AccCreSta" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BuyCreSta" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccCreWord" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccCreNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BuyCreWord" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BuyCreNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveBank" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RequestID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BuyRequestID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceNoticeXmlMap" Member="InvoiceNoticeXmlMap">
    <Type Name="InvoiceNoticeXmlMap">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InvoiceXmlID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DecListID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OutQty" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>