<?xml version="1.0" encoding="utf-8"?><Database Name="VAERP" Class="SqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.80.25,5311;Initial Catalog=VAERP;Persist Security Info=True;User ID=udata" SettingsObjectName="Layers.Data.Properties.Settings" SettingsPropertyName="VAERPConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DYJOrderFiles" Member="DYJOrderFiles">
    <Type Name="DYJOrderFiles">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DYJPurchases" Member="DYJPurchases">
    <Type Name="DYJPurchases">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChangeType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductTitle" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="MF_Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TradeDistrict" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EnterStorage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExitStorage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SalesCurrency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductPrice" Type="System.Decimal" DbType="Decimal(28,5) NOT NULL" CanBeNull="false" />
      <Column Name="SalesCurrency1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductPrice1" Type="System.Decimal" DbType="Decimal(28,5) NOT NULL" CanBeNull="false" />
      <Column Name="PurchasesCurrency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PurchasesPrice" Type="System.Decimal" DbType="Decimal(28,5) NOT NULL" CanBeNull="false" />
      <Column Name="PurchasesCurrency1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PurchasesPrice1" Type="System.Decimal" DbType="Decimal(28,5) NOT NULL" CanBeNull="false" />
      <Column Name="ProductBatch" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ProductPostting" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ProductSummary" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ShopType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Placer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tax" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Promoter" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SupplierBeneficiary" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="PurchaseCompany" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="OrderSummary" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="OLDDYJID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DYJID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DYJStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DYJStatus2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DYJMark" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="DYJCurrency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DYJPrice" Type="System.Decimal" DbType="Decimal(28,5)" CanBeNull="true" />
      <Column Name="DYJPrice1" Type="System.Decimal" DbType="Decimal(28,5)" CanBeNull="true" />
      <Column Name="LockStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Origin" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PoD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OldNoticeId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ServiceCode" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="CustomerPartCode" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DYJdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DYJClientCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DYJSupplierCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SupplierName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PurchaseType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Carrier" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Purchaser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliveryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PayType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SupplierBank" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SupplierBankAddress" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SupplierAccount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SupplierSwiftCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SupplierTax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SourceAgentId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QuoteCurrency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuotePrice" Type="System.Decimal" DbType="Decimal(28,5)" CanBeNull="true" />
      <Column Name="QuoteCurrency1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuotePrice1" Type="System.Decimal" DbType="Decimal(28,5)" CanBeNull="true" />
    </Type>
  </Table>
</Database>