<?xml version="1.0" encoding="utf-8"?><Database Name="PvbCrm" Class="sqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.30.10.51,6522;Initial Catalog=PvbCrm;Persist Security Info=True;User ID=u_v0" SettingsObjectName="Layer.Data.Properties.Settings" SettingsPropertyName="PvbCrmConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.WsClientsTopView" Member="WsClientsTopView">
    <Type Name="WsClientsTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="AdminCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Corporation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RegAddress" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Uscc" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Grade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Vip" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EnterCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CustomsCode" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>