#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layers.Data.Sqls._ForTests
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HvRFQ")]
	public partial class SqlsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertInquiries(Inquiries instance);
    partial void UpdateInquiries(Inquiries instance);
    partial void DeleteInquiries(Inquiries instance);
    partial void InsertAdmins(Admins instance);
    partial void UpdateAdmins(Admins instance);
    partial void DeleteAdmins(Admins instance);
    partial void InsertBoms(Boms instance);
    partial void UpdateBoms(Boms instance);
    partial void DeleteBoms(Boms instance);
    #endregion
		
		public SqlsDataContext() : 
				base(global::Layers.Data.Properties.Settings.Default.HvRFQConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public SqlsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SqlsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SqlsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SqlsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Inquiries> Inquiries
		{
			get
			{
				return this.GetTable<Inquiries>();
			}
		}
		
		public System.Data.Linq.Table<AdminsTopView> AdminsTopView
		{
			get
			{
				return this.GetTable<AdminsTopView>();
			}
		}
		
		public System.Data.Linq.Table<Admins> Admins
		{
			get
			{
				return this.GetTable<Admins>();
			}
		}
		
		public System.Data.Linq.Table<Boms> Boms
		{
			get
			{
				return this.GetTable<Boms>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Inquiries")]
	public partial class Inquiries : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _BomID;
		
		private string _InputID;
		
		private string _ClientID;
		
		private int _BussinessType;
		
		private int _District;
		
		private string _Contact;
		
		private string _ContactMobile;
		
		private string _Name;
		
		private string _Manufacturer;
		
		private bool _MfReplace;
		
		private int _MfRequirement;
		
		private int _ChannelRequirement;
		
		private string _Package;
		
		private string _Batch;
		
		private int _Quantity;
		
		private int _QuantityRemark;
		
		private int _TradeType;
		
		private System.DateTime _DeliveryDate;
		
		private int _Status;
		
		private string _Summary;
		
		private System.DateTime _CreateDate;
		
		private System.DateTime _UpdateDate;
		
		private bool _IsFocus;
		
		private string _AdminID;
		
		private int _ReplyTime;
		
		private System.DateTime _ReplyTimeDateTime;
		
		private System.Nullable<int> _PurchasingCycle;
		
		private System.Nullable<System.DateTime> _PurchasingCycleDateTime;
		
		private System.Nullable<bool> _NeedCCCCertificate;
		
		private System.Nullable<bool> _IsEmbargo;
		
		private System.Nullable<double> _TariffRate;
		
		private System.Nullable<bool> _IsInsp;
		
		private System.Nullable<double> _AddedTariffs;
		
		private System.Nullable<System.DateTime> _ApprovalDate;
		
		private System.Nullable<System.DateTime> _QuoteDate;
		
		private string _AgentID;
		
		private string _PriceID;
		
		private bool _IsFollow;
		
		private EntityRef<Boms> _Boms;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnBomIDChanging(string value);
    partial void OnBomIDChanged();
    partial void OnInputIDChanging(string value);
    partial void OnInputIDChanged();
    partial void OnClientIDChanging(string value);
    partial void OnClientIDChanged();
    partial void OnBussinessTypeChanging(int value);
    partial void OnBussinessTypeChanged();
    partial void OnDistrictChanging(int value);
    partial void OnDistrictChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnContactMobileChanging(string value);
    partial void OnContactMobileChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnManufacturerChanging(string value);
    partial void OnManufacturerChanged();
    partial void OnMfReplaceChanging(bool value);
    partial void OnMfReplaceChanged();
    partial void OnMfRequirementChanging(int value);
    partial void OnMfRequirementChanged();
    partial void OnChannelRequirementChanging(int value);
    partial void OnChannelRequirementChanged();
    partial void OnPackageChanging(string value);
    partial void OnPackageChanged();
    partial void OnBatchChanging(string value);
    partial void OnBatchChanged();
    partial void OnQuantityChanging(int value);
    partial void OnQuantityChanged();
    partial void OnQuantityRemarkChanging(int value);
    partial void OnQuantityRemarkChanged();
    partial void OnTradeTypeChanging(int value);
    partial void OnTradeTypeChanged();
    partial void OnDeliveryDateChanging(System.DateTime value);
    partial void OnDeliveryDateChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnSummaryChanging(string value);
    partial void OnSummaryChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnUpdateDateChanging(System.DateTime value);
    partial void OnUpdateDateChanged();
    partial void OnIsFocusChanging(bool value);
    partial void OnIsFocusChanged();
    partial void OnAdminIDChanging(string value);
    partial void OnAdminIDChanged();
    partial void OnReplyTimeChanging(int value);
    partial void OnReplyTimeChanged();
    partial void OnReplyTimeDateTimeChanging(System.DateTime value);
    partial void OnReplyTimeDateTimeChanged();
    partial void OnPurchasingCycleChanging(System.Nullable<int> value);
    partial void OnPurchasingCycleChanged();
    partial void OnPurchasingCycleDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnPurchasingCycleDateTimeChanged();
    partial void OnNeedCCCCertificateChanging(System.Nullable<bool> value);
    partial void OnNeedCCCCertificateChanged();
    partial void OnIsEmbargoChanging(System.Nullable<bool> value);
    partial void OnIsEmbargoChanged();
    partial void OnTariffRateChanging(System.Nullable<double> value);
    partial void OnTariffRateChanged();
    partial void OnIsInspChanging(System.Nullable<bool> value);
    partial void OnIsInspChanged();
    partial void OnAddedTariffsChanging(System.Nullable<double> value);
    partial void OnAddedTariffsChanged();
    partial void OnApprovalDateChanging(System.Nullable<System.DateTime> value);
    partial void OnApprovalDateChanged();
    partial void OnQuoteDateChanging(System.Nullable<System.DateTime> value);
    partial void OnQuoteDateChanged();
    partial void OnAgentIDChanging(string value);
    partial void OnAgentIDChanged();
    partial void OnPriceIDChanging(string value);
    partial void OnPriceIDChanged();
    partial void OnIsFollowChanging(bool value);
    partial void OnIsFollowChanged();
    #endregion
		
		public Inquiries()
		{
			this._Boms = default(EntityRef<Boms>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BomID", DbType="VarChar(50)")]
		public string BomID
		{
			get
			{
				return this._BomID;
			}
			set
			{
				if ((this._BomID != value))
				{
					if (this._Boms.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBomIDChanging(value);
					this.SendPropertyChanging();
					this._BomID = value;
					this.SendPropertyChanged("BomID");
					this.OnBomIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string InputID
		{
			get
			{
				return this._InputID;
			}
			set
			{
				if ((this._InputID != value))
				{
					this.OnInputIDChanging(value);
					this.SendPropertyChanging();
					this._InputID = value;
					this.SendPropertyChanged("InputID");
					this.OnInputIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this.OnClientIDChanging(value);
					this.SendPropertyChanging();
					this._ClientID = value;
					this.SendPropertyChanged("ClientID");
					this.OnClientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BussinessType", DbType="Int NOT NULL")]
		public int BussinessType
		{
			get
			{
				return this._BussinessType;
			}
			set
			{
				if ((this._BussinessType != value))
				{
					this.OnBussinessTypeChanging(value);
					this.SendPropertyChanging();
					this._BussinessType = value;
					this.SendPropertyChanged("BussinessType");
					this.OnBussinessTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="Int NOT NULL")]
		public int District
		{
			get
			{
				return this._District;
			}
			set
			{
				if ((this._District != value))
				{
					this.OnDistrictChanging(value);
					this.SendPropertyChanging();
					this._District = value;
					this.SendPropertyChanged("District");
					this.OnDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="NVarChar(150)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactMobile", DbType="VarChar(50)")]
		public string ContactMobile
		{
			get
			{
				return this._ContactMobile;
			}
			set
			{
				if ((this._ContactMobile != value))
				{
					this.OnContactMobileChanging(value);
					this.SendPropertyChanging();
					this._ContactMobile = value;
					this.SendPropertyChanged("ContactMobile");
					this.OnContactMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manufacturer", DbType="NVarChar(150)")]
		public string Manufacturer
		{
			get
			{
				return this._Manufacturer;
			}
			set
			{
				if ((this._Manufacturer != value))
				{
					this.OnManufacturerChanging(value);
					this.SendPropertyChanging();
					this._Manufacturer = value;
					this.SendPropertyChanged("Manufacturer");
					this.OnManufacturerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MfReplace", DbType="Bit NOT NULL")]
		public bool MfReplace
		{
			get
			{
				return this._MfReplace;
			}
			set
			{
				if ((this._MfReplace != value))
				{
					this.OnMfReplaceChanging(value);
					this.SendPropertyChanging();
					this._MfReplace = value;
					this.SendPropertyChanged("MfReplace");
					this.OnMfReplaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MfRequirement", DbType="Int NOT NULL")]
		public int MfRequirement
		{
			get
			{
				return this._MfRequirement;
			}
			set
			{
				if ((this._MfRequirement != value))
				{
					this.OnMfRequirementChanging(value);
					this.SendPropertyChanging();
					this._MfRequirement = value;
					this.SendPropertyChanged("MfRequirement");
					this.OnMfRequirementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChannelRequirement", DbType="Int NOT NULL")]
		public int ChannelRequirement
		{
			get
			{
				return this._ChannelRequirement;
			}
			set
			{
				if ((this._ChannelRequirement != value))
				{
					this.OnChannelRequirementChanging(value);
					this.SendPropertyChanging();
					this._ChannelRequirement = value;
					this.SendPropertyChanged("ChannelRequirement");
					this.OnChannelRequirementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Package", DbType="VarChar(50)")]
		public string Package
		{
			get
			{
				return this._Package;
			}
			set
			{
				if ((this._Package != value))
				{
					this.OnPackageChanging(value);
					this.SendPropertyChanging();
					this._Package = value;
					this.SendPropertyChanged("Package");
					this.OnPackageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Batch", DbType="VarChar(50)")]
		public string Batch
		{
			get
			{
				return this._Batch;
			}
			set
			{
				if ((this._Batch != value))
				{
					this.OnBatchChanging(value);
					this.SendPropertyChanging();
					this._Batch = value;
					this.SendPropertyChanged("Batch");
					this.OnBatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantityRemark", DbType="Int NOT NULL")]
		public int QuantityRemark
		{
			get
			{
				return this._QuantityRemark;
			}
			set
			{
				if ((this._QuantityRemark != value))
				{
					this.OnQuantityRemarkChanging(value);
					this.SendPropertyChanging();
					this._QuantityRemark = value;
					this.SendPropertyChanged("QuantityRemark");
					this.OnQuantityRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TradeType", DbType="Int NOT NULL")]
		public int TradeType
		{
			get
			{
				return this._TradeType;
			}
			set
			{
				if ((this._TradeType != value))
				{
					this.OnTradeTypeChanging(value);
					this.SendPropertyChanging();
					this._TradeType = value;
					this.SendPropertyChanged("TradeType");
					this.OnTradeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryDate", DbType="DateTime NOT NULL")]
		public System.DateTime DeliveryDate
		{
			get
			{
				return this._DeliveryDate;
			}
			set
			{
				if ((this._DeliveryDate != value))
				{
					this.OnDeliveryDateChanging(value);
					this.SendPropertyChanging();
					this._DeliveryDate = value;
					this.SendPropertyChanged("DeliveryDate");
					this.OnDeliveryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Summary", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Summary
		{
			get
			{
				return this._Summary;
			}
			set
			{
				if ((this._Summary != value))
				{
					this.OnSummaryChanging(value);
					this.SendPropertyChanging();
					this._Summary = value;
					this.SendPropertyChanged("Summary");
					this.OnSummaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime NOT NULL")]
		public System.DateTime UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFocus", DbType="Bit NOT NULL")]
		public bool IsFocus
		{
			get
			{
				return this._IsFocus;
			}
			set
			{
				if ((this._IsFocus != value))
				{
					this.OnIsFocusChanging(value);
					this.SendPropertyChanging();
					this._IsFocus = value;
					this.SendPropertyChanged("IsFocus");
					this.OnIsFocusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AdminID
		{
			get
			{
				return this._AdminID;
			}
			set
			{
				if ((this._AdminID != value))
				{
					this.OnAdminIDChanging(value);
					this.SendPropertyChanging();
					this._AdminID = value;
					this.SendPropertyChanged("AdminID");
					this.OnAdminIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplyTime", DbType="Int NOT NULL")]
		public int ReplyTime
		{
			get
			{
				return this._ReplyTime;
			}
			set
			{
				if ((this._ReplyTime != value))
				{
					this.OnReplyTimeChanging(value);
					this.SendPropertyChanging();
					this._ReplyTime = value;
					this.SendPropertyChanged("ReplyTime");
					this.OnReplyTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplyTimeDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime ReplyTimeDateTime
		{
			get
			{
				return this._ReplyTimeDateTime;
			}
			set
			{
				if ((this._ReplyTimeDateTime != value))
				{
					this.OnReplyTimeDateTimeChanging(value);
					this.SendPropertyChanging();
					this._ReplyTimeDateTime = value;
					this.SendPropertyChanged("ReplyTimeDateTime");
					this.OnReplyTimeDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchasingCycle", DbType="Int")]
		public System.Nullable<int> PurchasingCycle
		{
			get
			{
				return this._PurchasingCycle;
			}
			set
			{
				if ((this._PurchasingCycle != value))
				{
					this.OnPurchasingCycleChanging(value);
					this.SendPropertyChanging();
					this._PurchasingCycle = value;
					this.SendPropertyChanged("PurchasingCycle");
					this.OnPurchasingCycleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchasingCycleDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> PurchasingCycleDateTime
		{
			get
			{
				return this._PurchasingCycleDateTime;
			}
			set
			{
				if ((this._PurchasingCycleDateTime != value))
				{
					this.OnPurchasingCycleDateTimeChanging(value);
					this.SendPropertyChanging();
					this._PurchasingCycleDateTime = value;
					this.SendPropertyChanged("PurchasingCycleDateTime");
					this.OnPurchasingCycleDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NeedCCCCertificate", DbType="Bit")]
		public System.Nullable<bool> NeedCCCCertificate
		{
			get
			{
				return this._NeedCCCCertificate;
			}
			set
			{
				if ((this._NeedCCCCertificate != value))
				{
					this.OnNeedCCCCertificateChanging(value);
					this.SendPropertyChanging();
					this._NeedCCCCertificate = value;
					this.SendPropertyChanged("NeedCCCCertificate");
					this.OnNeedCCCCertificateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEmbargo", DbType="Bit")]
		public System.Nullable<bool> IsEmbargo
		{
			get
			{
				return this._IsEmbargo;
			}
			set
			{
				if ((this._IsEmbargo != value))
				{
					this.OnIsEmbargoChanging(value);
					this.SendPropertyChanging();
					this._IsEmbargo = value;
					this.SendPropertyChanged("IsEmbargo");
					this.OnIsEmbargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TariffRate", DbType="Float")]
		public System.Nullable<double> TariffRate
		{
			get
			{
				return this._TariffRate;
			}
			set
			{
				if ((this._TariffRate != value))
				{
					this.OnTariffRateChanging(value);
					this.SendPropertyChanging();
					this._TariffRate = value;
					this.SendPropertyChanged("TariffRate");
					this.OnTariffRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsInsp", DbType="Bit")]
		public System.Nullable<bool> IsInsp
		{
			get
			{
				return this._IsInsp;
			}
			set
			{
				if ((this._IsInsp != value))
				{
					this.OnIsInspChanging(value);
					this.SendPropertyChanging();
					this._IsInsp = value;
					this.SendPropertyChanged("IsInsp");
					this.OnIsInspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedTariffs", DbType="Float")]
		public System.Nullable<double> AddedTariffs
		{
			get
			{
				return this._AddedTariffs;
			}
			set
			{
				if ((this._AddedTariffs != value))
				{
					this.OnAddedTariffsChanging(value);
					this.SendPropertyChanging();
					this._AddedTariffs = value;
					this.SendPropertyChanged("AddedTariffs");
					this.OnAddedTariffsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ApprovalDate
		{
			get
			{
				return this._ApprovalDate;
			}
			set
			{
				if ((this._ApprovalDate != value))
				{
					this.OnApprovalDateChanging(value);
					this.SendPropertyChanging();
					this._ApprovalDate = value;
					this.SendPropertyChanged("ApprovalDate");
					this.OnApprovalDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuoteDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> QuoteDate
		{
			get
			{
				return this._QuoteDate;
			}
			set
			{
				if ((this._QuoteDate != value))
				{
					this.OnQuoteDateChanging(value);
					this.SendPropertyChanging();
					this._QuoteDate = value;
					this.SendPropertyChanged("QuoteDate");
					this.OnQuoteDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AgentID
		{
			get
			{
				return this._AgentID;
			}
			set
			{
				if ((this._AgentID != value))
				{
					this.OnAgentIDChanging(value);
					this.SendPropertyChanging();
					this._AgentID = value;
					this.SendPropertyChanged("AgentID");
					this.OnAgentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceID", DbType="VarChar(50)")]
		public string PriceID
		{
			get
			{
				return this._PriceID;
			}
			set
			{
				if ((this._PriceID != value))
				{
					this.OnPriceIDChanging(value);
					this.SendPropertyChanging();
					this._PriceID = value;
					this.SendPropertyChanged("PriceID");
					this.OnPriceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFollow", DbType="Bit NOT NULL")]
		public bool IsFollow
		{
			get
			{
				return this._IsFollow;
			}
			set
			{
				if ((this._IsFollow != value))
				{
					this.OnIsFollowChanging(value);
					this.SendPropertyChanging();
					this._IsFollow = value;
					this.SendPropertyChanged("IsFollow");
					this.OnIsFollowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Boms_Inquiries", Storage="_Boms", ThisKey="BomID", OtherKey="ID", IsForeignKey=true)]
		public Boms Boms
		{
			get
			{
				return this._Boms.Entity;
			}
			set
			{
				Boms previousValue = this._Boms.Entity;
				if (((previousValue != value) 
							|| (this._Boms.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Boms.Entity = null;
						previousValue.Inquiries.Remove(this);
					}
					this._Boms.Entity = value;
					if ((value != null))
					{
						value.Inquiries.Add(this);
						this._BomID = value.ID;
					}
					else
					{
						this._BomID = default(string);
					}
					this.SendPropertyChanged("Boms");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdminsTopView")]
	public partial class AdminsTopView
	{
		
		private string _ID;
		
		private string _StaffID;
		
		private string _UserName;
		
		private string _RealName;
		
		private string _SelCode;
		
		private int _Status;
		
		private System.Nullable<System.DateTime> _LastLoginDate;
		
		private string _RoleID;
		
		private string _RoleName;
		
		private System.Nullable<int> _RoleStatus;
		
		public AdminsTopView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffID", DbType="VarChar(50)")]
		public string StaffID
		{
			get
			{
				return this._StaffID;
			}
			set
			{
				if ((this._StaffID != value))
				{
					this._StaffID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this._RealName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SelCode
		{
			get
			{
				return this._SelCode;
			}
			set
			{
				if ((this._SelCode != value))
				{
					this._SelCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLoginDate
		{
			get
			{
				return this._LastLoginDate;
			}
			set
			{
				if ((this._LastLoginDate != value))
				{
					this._LastLoginDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="VarChar(50)")]
		public string RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this._RoleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(150)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this._RoleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleStatus", DbType="Int")]
		public System.Nullable<int> RoleStatus
		{
			get
			{
				return this._RoleStatus;
			}
			set
			{
				if ((this._RoleStatus != value))
				{
					this._RoleStatus = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admins")]
	public partial class Admins : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _StaffID;
		
		private string _UserName;
		
		private string _RealName;
		
		private string _ShowName;
		
		private string _Password;
		
		private string _SelCode;
		
		private string _RoleID;
		
		private System.DateTime _CreateDate;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private int _Status;
		
		private System.Nullable<System.DateTime> _LastLoginDate;
		
		private string _OriginID;
		
		private System.Nullable<System.DateTime> _PwdModifyDate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnStaffIDChanging(string value);
    partial void OnStaffIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnRealNameChanging(string value);
    partial void OnRealNameChanged();
    partial void OnShowNameChanging(string value);
    partial void OnShowNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnSelCodeChanging(string value);
    partial void OnSelCodeChanged();
    partial void OnRoleIDChanging(string value);
    partial void OnRoleIDChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnLastLoginDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLoginDateChanged();
    partial void OnOriginIDChanging(string value);
    partial void OnOriginIDChanged();
    partial void OnPwdModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPwdModifyDateChanged();
    #endregion
		
		public Admins()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffID", DbType="VarChar(50)")]
		public string StaffID
		{
			get
			{
				return this._StaffID;
			}
			set
			{
				if ((this._StaffID != value))
				{
					this.OnStaffIDChanging(value);
					this.SendPropertyChanging();
					this._StaffID = value;
					this.SendPropertyChanged("StaffID");
					this.OnStaffIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this.OnRealNameChanging(value);
					this.SendPropertyChanging();
					this._RealName = value;
					this.SendPropertyChanged("RealName");
					this.OnRealNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowName", DbType="NVarChar(50)")]
		public string ShowName
		{
			get
			{
				return this._ShowName;
			}
			set
			{
				if ((this._ShowName != value))
				{
					this.OnShowNameChanging(value);
					this.SendPropertyChanging();
					this._ShowName = value;
					this.SendPropertyChanged("ShowName");
					this.OnShowNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SelCode
		{
			get
			{
				return this._SelCode;
			}
			set
			{
				if ((this._SelCode != value))
				{
					this.OnSelCodeChanging(value);
					this.SendPropertyChanging();
					this._SelCode = value;
					this.SendPropertyChanged("SelCode");
					this.OnSelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="VarChar(50)")]
		public string RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLoginDate
		{
			get
			{
				return this._LastLoginDate;
			}
			set
			{
				if ((this._LastLoginDate != value))
				{
					this.OnLastLoginDateChanging(value);
					this.SendPropertyChanging();
					this._LastLoginDate = value;
					this.SendPropertyChanged("LastLoginDate");
					this.OnLastLoginDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginID", DbType="VarChar(50)")]
		public string OriginID
		{
			get
			{
				return this._OriginID;
			}
			set
			{
				if ((this._OriginID != value))
				{
					this.OnOriginIDChanging(value);
					this.SendPropertyChanging();
					this._OriginID = value;
					this.SendPropertyChanged("OriginID");
					this.OnOriginIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PwdModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PwdModifyDate
		{
			get
			{
				return this._PwdModifyDate;
			}
			set
			{
				if ((this._PwdModifyDate != value))
				{
					this.OnPwdModifyDateChanging(value);
					this.SendPropertyChanging();
					this._PwdModifyDate = value;
					this.SendPropertyChanged("PwdModifyDate");
					this.OnPwdModifyDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Boms")]
	public partial class Boms : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _ClientID;
		
		private int _BussinessType;
		
		private int _District;
		
		private string _Contact;
		
		private string _ContactMobile;
		
		private string _AdminID;
		
		private int _Status;
		
		private string _Summary;
		
		private System.DateTime _CreateDate;
		
		private System.DateTime _UpdateDate;
		
		private string _AgentID;
		
		private EntitySet<Inquiries> _Inquiries;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnClientIDChanging(string value);
    partial void OnClientIDChanged();
    partial void OnBussinessTypeChanging(int value);
    partial void OnBussinessTypeChanged();
    partial void OnDistrictChanging(int value);
    partial void OnDistrictChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnContactMobileChanging(string value);
    partial void OnContactMobileChanged();
    partial void OnAdminIDChanging(string value);
    partial void OnAdminIDChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnSummaryChanging(string value);
    partial void OnSummaryChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnUpdateDateChanging(System.DateTime value);
    partial void OnUpdateDateChanged();
    partial void OnAgentIDChanging(string value);
    partial void OnAgentIDChanged();
    #endregion
		
		public Boms()
		{
			this._Inquiries = new EntitySet<Inquiries>(new Action<Inquiries>(this.attach_Inquiries), new Action<Inquiries>(this.detach_Inquiries));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this.OnClientIDChanging(value);
					this.SendPropertyChanging();
					this._ClientID = value;
					this.SendPropertyChanged("ClientID");
					this.OnClientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BussinessType", DbType="Int NOT NULL")]
		public int BussinessType
		{
			get
			{
				return this._BussinessType;
			}
			set
			{
				if ((this._BussinessType != value))
				{
					this.OnBussinessTypeChanging(value);
					this.SendPropertyChanging();
					this._BussinessType = value;
					this.SendPropertyChanged("BussinessType");
					this.OnBussinessTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="Int NOT NULL")]
		public int District
		{
			get
			{
				return this._District;
			}
			set
			{
				if ((this._District != value))
				{
					this.OnDistrictChanging(value);
					this.SendPropertyChanging();
					this._District = value;
					this.SendPropertyChanged("District");
					this.OnDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactMobile", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ContactMobile
		{
			get
			{
				return this._ContactMobile;
			}
			set
			{
				if ((this._ContactMobile != value))
				{
					this.OnContactMobileChanging(value);
					this.SendPropertyChanging();
					this._ContactMobile = value;
					this.SendPropertyChanged("ContactMobile");
					this.OnContactMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AdminID
		{
			get
			{
				return this._AdminID;
			}
			set
			{
				if ((this._AdminID != value))
				{
					this.OnAdminIDChanging(value);
					this.SendPropertyChanging();
					this._AdminID = value;
					this.SendPropertyChanged("AdminID");
					this.OnAdminIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Summary", DbType="NVarChar(300)")]
		public string Summary
		{
			get
			{
				return this._Summary;
			}
			set
			{
				if ((this._Summary != value))
				{
					this.OnSummaryChanging(value);
					this.SendPropertyChanging();
					this._Summary = value;
					this.SendPropertyChanged("Summary");
					this.OnSummaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime NOT NULL")]
		public System.DateTime UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AgentID
		{
			get
			{
				return this._AgentID;
			}
			set
			{
				if ((this._AgentID != value))
				{
					this.OnAgentIDChanging(value);
					this.SendPropertyChanging();
					this._AgentID = value;
					this.SendPropertyChanged("AgentID");
					this.OnAgentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Boms_Inquiries", Storage="_Inquiries", ThisKey="ID", OtherKey="BomID")]
		public EntitySet<Inquiries> Inquiries
		{
			get
			{
				return this._Inquiries;
			}
			set
			{
				this._Inquiries.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Inquiries(Inquiries entity)
		{
			this.SendPropertyChanging();
			entity.Boms = this;
		}
		
		private void detach_Inquiries(Inquiries entity)
		{
			this.SendPropertyChanging();
			entity.Boms = null;
		}
	}
}
#pragma warning restore 1591
