<?xml version="1.0" encoding="utf-8"?><Database Name="PsOrder" Class="sqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.30.10.51,6522;Initial Catalog=PsOrder;Persist Security Info=True;User ID=u_v0" SettingsObjectName="Layers.Data.Properties.Settings" SettingsPropertyName="PsOrderConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StandardProducts" Member="StandardProducts">
    <Type Name="StandardProducts">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Partnumber" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Package" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mpq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Moq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.OrderPermiuns" Member="OrderPermiuns">
    <Type Name="OrderPermiuns">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Conduct" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Currency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(22,10)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(22,10)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AdminCreatorID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PayeeLefts" Member="PayeeLefts">
    <Type Name="PayeeLefts">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Source" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PayerID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PayeeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Conduct" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(22,10) NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(22,10) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CutDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CutDateIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoticeID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FormID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WaybillCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VoucherID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Products">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Partnumber" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Package" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mpq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Moq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Requires" Member="Requires">
    <Type Name="Requires">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderTransportID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Siteusers" Member="Siteusers">
    <Type Name="Siteusers">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Orders">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SiteuserID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ConsigneeID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ConsignorID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PackageCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.OrderTransports" Member="OrderTransports">
    <Type Name="OrderTransports">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TransportMode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Carrier" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WaybillCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ExpressPayer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpressTransport" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ExpressEscrow" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TakingTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PickerID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pickers" Member="Pickers">
    <Type Name="Pickers">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PcFiles" Member="PcFiles">
    <Type Name="PcFiles">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MainID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SiteuserID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Logs" Member="Logs">
    <Type Name="Logs">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ActionName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MainID" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserTokens" Member="UserTokens">
    <Type Name="UserTokens">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Token" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoices" Member="Invoices">
    <Type Name="Invoices">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TaxNumber" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="RegAddress" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BankAccount" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RevAddress" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PayerLeftsTopView" Member="PayerLeftsTopView">
    <Type Name="PayerLeftsTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Source" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PayerID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PayeeID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TakerID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Conduct" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(22,10) NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(22,10) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CutDateIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoticeID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FormID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WaybillCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Addresses" Member="Addresses">
    <Type Name="Addresses">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DeliveryTopViewTest" Member="DeliveryTopViewTest">
    <Type Name="DeliveryTopViewTest">
      <Column Name="StoragePackageNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StorageTotal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FormID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FormItemID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Partnumber" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Package" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mpq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoticeItemID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StoragesTopView" Member="StoragesTopView">
    <Type Name="StoragesTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Islock" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="StocktakingType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mpq" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PackageNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Partnumber" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Package" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ShelveID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ex_PackageNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Supplier" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderItems" Member="OrderItems">
    <Type Name="OrderItems">
      <Column Name="ID" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Supplier" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Origin" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CustomCode" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="StocktakingType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mpq" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PackageNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(22,10)" CanBeNull="true" />
      <Column Name="StorageID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BakPartnumber" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="BakBrand" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="BakPackage" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BakDateCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NoticeID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NoticeItemID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InputID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeliveryTopView" Member="DeliveryTopView">
    <Type Name="DeliveryTopView">
      <Column Name="InputID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StoragePackageNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StorageTotal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FormID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FormItemID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Partnumber" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Package" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mpq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoticeItemID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NoticeTransportsTopView" Member="NoticeTransportsTopView">
    <Type Name="NoticeTransportsTopView">
      <Column Name="NoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoticeType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FormID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NoticeTransportID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TransportMode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Carrier" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WaybillCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ExpressPayer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExpressTransport" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExpressEscrow" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ExpressFreight" Type="System.Decimal" DbType="Decimal(22,10) NOT NULL" CanBeNull="false" />
      <Column Name="TakingTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TakerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TakerLicense" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TakerPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TakerIDType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TakerIDCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PayeeRights" Member="PayeeRights">
    <Type Name="PayeeRights">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LeftID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(22,10) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReviewerID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FlowFormCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vouchers" Member="Vouchers">
    <Type Name="Vouchers">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PayerID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PayeeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="CutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CutDateIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsInvoiced" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Clients" Member="Clients">
    <Type Name="Clients">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SiteuserID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TrackerID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ServiceManagerID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SzInvoiceNoticeItemsTopView" Member="SzInvoiceNoticeItemsTopView">
    <Type Name="SzInvoiceNoticeItemsTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceNoticeID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BillID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="Difference" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="InvoiceNo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdminsTopView" Member="AdminsTopView">
    <Type Name="AdminsTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="RealName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SelCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RoleID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RoleStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OriginID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SzInvoiceNoticesTopView" Member="SzInvoiceNoticesTopView">
    <Type Name="SzInvoiceNoticesTopView">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsPersonal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FromType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TaxNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RegAddress" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BankAccount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PostAddress" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PostRecipient" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostTel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliveryType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Carrier" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WayBillCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MonoPriNoIncVarchar" Member="MonoPriNoIncVarchar">
    <Type Name="MonoPriNoIncVarchar">
      <Column Name="MainID0" Type="System.String" DbType="VarChar(1000) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ColVarchar" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="ColVarcharNull" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ColNvarchar" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="ColNvarcharNull" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ColInt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ColIntNull" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ColDatetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ColDatetimeNull" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ColDecimal" Type="System.Decimal" DbType="Decimal(22,10) NOT NULL" CanBeNull="false" />
      <Column Name="ColDecimalNull" Type="System.Decimal" DbType="Decimal(22,10)" CanBeNull="true" />
      <Column Name="ColBit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ColBitNull" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ColDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ColDateNull" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ColBigint" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ColBigintNull" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MonoPriA" Member="MonoPriA">
    <Type Name="MonoPriA">
      <Column Name="A1" Type="System.String" DbType="NVarChar(250) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="A2" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="MonoPriB_MonoPriA" Member="MonoPriB" ThisKey="A2" OtherKey="B1" Type="MonoPriB" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MonoPriB" Member="MonoPriB">
    <Type Name="MonoPriB">
      <Column Name="B1" Type="System.String" DbType="NVarChar(250) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="B2" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="MonoPriB_MonoPriA" Member="MonoPriA" ThisKey="B1" OtherKey="A2" Type="MonoPriA" />
    </Type>
  </Table>
</Database>