<?xml version="1.0" encoding="utf-8"?><Database Name="PvData" Class="sqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.30.10.199,5311;Initial Catalog=PvData;Persist Security Info=True;User ID=udata" SettingsObjectName="Yahv.PvData.ExchangeRates.Properties.Settings" SettingsPropertyName="PvDataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ExchangeRates" Member="ExchangeRates">
    <Type Name="ExchangeRates">
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="District" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[From]" Member="From" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[To]" Member="To" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Feroboc" Member="Feroboc">
    <Type Name="Feroboc">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Xhmr" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="Xcmr" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="Xhmc" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="Xcmc" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="Zhzsj" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="PublishDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>