<?xml version="1.0" encoding="utf-8"?><Database Name="PvOveralls" Class="SqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.80.25,5311;Initial Catalog=PvOveralls;Persist Security Info=True;User ID=udata" SettingsObjectName="Layers.Data.Properties.Settings" SettingsPropertyName="PvOverallsConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ExchangeRates" Member="ExchangeRates">
    <Type Name="ExchangeRates">
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="District" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[From]" Member="From" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[To]" Member="To" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Settings">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DataType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>