<?xml version="1.0" encoding="utf-8"?><Database Name="PSL" Class="PSLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.30.10.199,5311;Initial Catalog=PSL;Persist Security Info=True;User ID=udata" SettingsObjectName="Yahv.PSLToSolrData.Import.Properties.Settings" SettingsPropertyName="PSLConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Categories">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FatherID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NameCN" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="NameEN" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Categories_MapsCategory" Member="MapsCategory" ThisKey="ID" OtherKey="CategoryID" Type="MapsCategory" />
    </Type>
  </Table>
  <Table Name="dbo.MapsCategory" Member="MapsCategory">
    <Type Name="MapsCategory">
      <Column Name="ProductID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Categories_MapsCategory" Member="Categories" ThisKey="CategoryID" OtherKey="ID" Type="Categories" IsForeignKey="true" />
      <Association Name="Products_MapsCategory" Member="Products" ThisKey="ProductID" OtherKey="ID" Type="Products" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductDeliveries" Member="ProductDeliveries">
    <Type Name="ProductDeliveries">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Moq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Jump" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mpa" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="MpaCurrency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Delivery" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ProductInventories_ProductDeliveries" Member="ProductInventories" ThisKey="ID" OtherKey="ID" Type="ProductInventories" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductFiles" Member="ProductFiles">
    <Type Name="ProductFiles">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Uri" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Products_ProductFiles" Member="Products" ThisKey="ProductID" OtherKey="ID" Type="Products" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductInventories" Member="ProductInventories">
    <Type Name="ProductInventories">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Supplier" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Storage" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Packaging" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sign" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ProductInventories_ProductDeliveries" Member="ProductDeliveries" ThisKey="ID" OtherKey="ID" Type="ProductDeliveries" Cardinality="One" />
      <Association Name="ProductInventories_ProductQuotes" Member="ProductQuotes" ThisKey="ID" OtherKey="InventoryID" Type="ProductQuotes" />
      <Association Name="Products_ProductInventories" Member="Products" ThisKey="ProductID" OtherKey="ID" Type="Products" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductOrigins" Member="ProductOrigins">
    <Type Name="ProductOrigins">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Language" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Products_ProductOrigins" Member="Products" ThisKey="ProductID" OtherKey="ID" Type="Products" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductOthers" Member="ProductOthers">
    <Type Name="ProductOthers">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Language" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Products_ProductOthers" Member="Products" ThisKey="ProductID" OtherKey="ID" Type="Products" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductProperties" Member="ProductProperties">
    <Type Name="ProductProperties">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Language" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Products_ProductProperties" Member="Products" ThisKey="ProductID" OtherKey="ID" Type="Products" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductQuotes" Member="ProductQuotes">
    <Type Name="ProductQuotes">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InventoryID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Moq" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsCurrent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ProductInventories_ProductQuotes" Member="ProductInventories" ThisKey="InventoryID" OtherKey="ID" Type="ProductInventories" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Products">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PartNumber" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Manufacturer" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PackageCase" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Products_MapsCategory" Member="MapsCategory" ThisKey="ID" OtherKey="ProductID" Type="MapsCategory" />
      <Association Name="Products_ProductFiles" Member="ProductFiles" ThisKey="ID" OtherKey="ProductID" Type="ProductFiles" />
      <Association Name="Products_ProductInventories" Member="ProductInventories" ThisKey="ID" OtherKey="ProductID" Type="ProductInventories" />
      <Association Name="Products_ProductOrigins" Member="ProductOrigins" ThisKey="ID" OtherKey="ProductID" Type="ProductOrigins" />
      <Association Name="Products_ProductOthers" Member="ProductOthers" ThisKey="ID" OtherKey="ProductID" Type="ProductOthers" />
      <Association Name="Products_ProductProperties" Member="ProductProperties" ThisKey="ID" OtherKey="ProductID" Type="ProductProperties" />
    </Type>
  </Table>
</Database>