<?xml version="1.0" encoding="utf-8"?><Database Name="VASSO" Class="SqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.80.25;Initial Catalog=VASSO;User ID=udata" SettingsObjectName="Layer.Data.Properties.Settings" SettingsPropertyName="VASSOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Accounts" Member="Accounts">
    <Type Name="Accounts">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlatformID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SiteformID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Business" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SerialNumber" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="DateIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>