<?xml version="1.0" encoding="utf-8"?><Database Name="foricDBS" Class="foricDBSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.30.10.51,6522;Initial Catalog=foricDBS;Persist Security Info=True;User ID=u_v0" SettingsObjectName="Layer.Data.Properties.Settings" SettingsPropertyName="foricDBSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ApiLogs" Member="ApiLogs">
    <Type Name="ApiLogs">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TransactionName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="msgId" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="RequestContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ResponseContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BackOfficeRejectionCode" Member="BackOfficeRejectionCode">
    <Type Name="BackOfficeRejectionCode">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TransactionName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ENGDescription" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CHNDescription" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FXRequest" Member="FXRequest">
    <Type Name="FXRequest">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TransactionName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="msgId" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="orgId" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="ccyPair" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="dealtSide" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="txnAmount" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="txnCcy" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="tenor" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="clientTxnsId" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="uid" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="txnPurpose" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="underlyingCode" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GatewayRejectionCode" Member="GatewayRejectionCode">
    <Type Name="GatewayRejectionCode">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TransactionName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HttpCode" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ENGDescription" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CHNDescription" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GatewayResponse" Member="GatewayResponse">
    <Type Name="GatewayResponse">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="msgId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="timeStamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="code" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DBSstatus" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TSTResponse" Member="TSTResponse">
    <Type Name="TSTResponse">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TransactionName" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="msgId" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="orgId" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="noOfTxs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="totalTxnAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ctry" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="responseType" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="customerReference" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="msgRefId" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="txnRefId" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="bankReference" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="txnType" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="txnStatus" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="txnRejectCode" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="txnStatusDescription" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="txnCcy" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="txnAmount" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="debitAccountCcy" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="tranSettlementAmt" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="tranSettlementDt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fxContractRef1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fxAmountUtilized1" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="fxContractRef2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fxAmountUtilized2" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="senderName" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="senderSwiftBic" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="receivingName" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="receivingAccountNo" Type="System.String" DbType="VarChar(34)" CanBeNull="true" />
      <Column Name="receivingBankCtryCode" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="receivingSwiftBic" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="receivingBankName" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="addresses" Type="System.String" DbType="NVarChar(108)" CanBeNull="true" />
      <Column Name="transactionReference" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="isAllMatched" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BOPCode" Member="BOPCode">
    <Type Name="BOPCode">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AccountFlow" Member="AccountFlow">
    <Type Name="AccountFlow">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="msgId" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="accountNo" Type="System.String" DbType="VarChar(34) NOT NULL" CanBeNull="false" />
      <Column Name="accountCcy" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="availableBal" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="initiatingPartyName" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="drCrInd" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="txnCode" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="txnDesc" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="txnDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="valueDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="txnCcy" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="txnAmount" Type="System.Decimal" DbType="Decimal(20,8) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TSTRequest" Member="TSTRequest">
    <Type Name="TSTRequest">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TransactionName" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="msgId" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="orgId" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="timeStamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ctry" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="noOfTxs" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="totalTxnAmount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="customerReference" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="txnType" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="txnDate" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="txnCcy" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="txnAmount" Type="System.Decimal" DbType="Decimal(11,2) NOT NULL" CanBeNull="false" />
      <Column Name="debitAccountCcy" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="debitAccountAmount" Type="System.Decimal" DbType="Decimal(11,2) NOT NULL" CanBeNull="false" />
      <Column Name="fxContractRef1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fxAmountUtilized1" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="fxContractRef2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fxAmountUtilized2" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="chargeBearer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="senderName" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="senderAccountNo" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="senderBankCtryCode" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="senderSwiftBic" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="receivingName" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="receivingAccountNo" Type="System.String" DbType="VarChar(34) NOT NULL" CanBeNull="false" />
      <Column Name="receivingBankCtryCode" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="receivingClearingCode" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="receivingSwiftBic" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="receivingRoutingCode" Type="System.String" DbType="VarChar(31)" CanBeNull="true" />
      <Column Name="receivingBankName" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
      <Column Name="receivingBankAddress" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
      <Column Name="addresses" Type="System.String" DbType="NVarChar(108)" CanBeNull="true" />
      <Column Name="countrySpecific" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="intermediarySwiftBic" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="mode" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="emails" Type="System.String" DbType="VarChar(380)" CanBeNull="true" />
      <Column Name="phoneNumbers" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="paymentDetails" Type="System.String" DbType="NVarChar(144)" CanBeNull="true" />
      <Column Name="clientReferences" Type="System.String" DbType="NVarChar(282)" CanBeNull="true" />
      <Column Name="invoices" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="specificPaymentPurpose" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="taxFreeGoodsRelated" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="paymentNature" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="referenceNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="bOPCode1PaymentCategory" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="bOPCode1SeriesCode" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ApiClients" Member="ApiClients">
    <Type Name="ApiClients">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccountName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FXResponse" Member="FXResponse">
    <Type Name="FXResponse">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TransactionName" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="msgId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="orgId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="bookingStatus" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="txnRefId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="txnDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="uid" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="custProfile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="validTill" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ccyPair" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="txnAmount" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="txnCcy" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="contraCcy" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="contraAmount" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="dealtSide" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="rate" Type="System.Decimal" DbType="Decimal(9,6)" CanBeNull="true" />
      <Column Name="tenor" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="valueDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="dealType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="clientTxnsId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="txnStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="traceId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="txnRejectCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="txnStatusDescription" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="isLocked" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isACT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isTT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>